/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:11:55 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 20, pricingEngine_CustomerType0, true, "", true, 0);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=20, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(20, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2037.6, (-1741), pricingEngine_CustomerType0, true, "", true, (-1741));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5, 0, pricingEngine_CustomerType0, true, "ZIW60-TI", false, 5);
      assertEquals("PricingRequest[basePrice=5.0, quantity=0, customerType=REGULAR, seasonalSale=true, couponCode=ZIW60-TI, firstOrder=false, loyaltyPoints=5]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4689.2397, 1309, pricingEngine_CustomerType0, true, "SAVE10", true, 1309);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=4689.2397, quantity=1309, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=1309]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(620.1117046375434, 3624, pricingEngine_CustomerType0, false, "FLAT5", false, 3624);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals("PricingRequest[basePrice=620.1117046375434, quantity=3624, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=3624]", pricingEngine_PricingRequest0.toString());
      assertEquals(3624, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 1557, pricingEngine_CustomerType0, false, "v48d", false, 1557);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals("PricingRequest[basePrice=0.0, quantity=1557, customerType=REGULAR, seasonalSale=false, couponCode=v48d, firstOrder=false, loyaltyPoints=1557]", pricingEngine_PricingRequest0.toString());
      assertEquals(1557, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.35, 1197, pricingEngine_CustomerType0, false, "C|H+,RMZ&q/", false, 1197);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=0.35, quantity=1197, customerType=REGULAR, seasonalSale=false, couponCode=C|H+,RMZ&q/, firstOrder=false, loyaltyPoints=1197]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 2141601702, pricingEngine_CustomerType0, false, (String) null, false, 0);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=0.0, quantity=2141601702, customerType=REGULAR, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(620.1117046375434, 3624, pricingEngine_CustomerType0, false, "FLAT5", false, 3624);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=620.1117046375434, quantity=3624, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=3624]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(620.1117046375434, 3624, pricingEngine_CustomerType0, false, "FLAT5", false, 3624);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=620.1117046375434, quantity=3624, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=3624]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 1991, pricingEngine_CustomerType0, false, "FREESHIP", false, 4661);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=1991, customerType=VIP, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=4661]", pricingEngine_PricingRequest0.toString());
      assertEquals(4661, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1991, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(20, 20, pricingEngine_CustomerType0, true, "FLAT5", true, 20);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(20, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=20.0, quantity=20, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=20]", pricingEngine_PricingRequest0.toString());
      assertEquals(262.99, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1107, pricingEngine_CustomerType0, false, "SAVE10", false, 1107);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(727.54, double0, 0.01);
      assertEquals(1107, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=1.0, quantity=1107, customerType=VIP, seasonalSale=false, couponCode=SAVE10, firstOrder=false, loyaltyPoints=1107]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 992, pricingEngine_CustomerType0, true, "SAVE10", true, 992);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=992, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=992]", pricingEngine_PricingRequest0.toString());
      assertEquals(992, pricingEngine_PricingRequest0.quantity());
      assertEquals(992, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2001, 2001, pricingEngine_CustomerType0, false, (String) null, false, 2001);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2001, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(2922928.72, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(19, 19, pricingEngine_CustomerType0, false, "FREESHIP", false, 19);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(19, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(324.9, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(3, 3, pricingEngine_CustomerType0, true, "", true, 3);
      assertEquals(3.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=3.0, quantity=3, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=3]", pricingEngine_PricingRequest0.toString());
      assertEquals(3, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(14.11, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1960, 1960, pricingEngine_CustomerType0, true, "COM.VIKTOR.LAB4.PRICINGENGINE$PRICINGREQUEST", true, (-835));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 1960, (PricingEngine.CustomerType) null, false, "FREESHIP", false, 0);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1991, 0, pricingEngine_CustomerType0, true, "oGH$p *k", true, (-424));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-1166), (-2268), pricingEngine_CustomerType0, true, "8t2b5q{ZQ-RG&xr8$", true, 1);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4689.2397, 1309, pricingEngine_CustomerType0, true, "SAVE10", true, 1309);
      Object object0 = new Object();
      pricingEngine_PricingRequest0.equals(object0);
      assertEquals("PricingRequest[basePrice=4689.2397, quantity=1309, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=1309]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4689.2397, 1309, pricingEngine_CustomerType0, true, "SAVE10", true, 1309);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=4689.2397, quantity=1309, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=1309]", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 1960, pricingEngine_CustomerType0, true, "flat5", true, 1960);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1960, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1960, pricingEngine_PricingRequest0.quantity());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals("PricingRequest[basePrice=0.0, quantity=1960, customerType=VIP, seasonalSale=true, couponCode=flat5, firstOrder=true, loyaltyPoints=1960]", pricingEngine_PricingRequest0.toString());
  }
}
