/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:13:04 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, true, "FREESHIP", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(65.0, double0, 0.01);
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=VIP, seasonalSale=true, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 0, pricingEngine_CustomerType0, true, "", true, 0);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.03, 1, pricingEngine_CustomerType0, false, "m\"zhYgx[", false, 1);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals(1, int0);
      assertEquals("PricingRequest[basePrice=0.03, quantity=1, customerType=REGULAR, seasonalSale=false, couponCode=m\"zhYgx[, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
      assertEquals(100, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(568.43, 20, pricingEngine_CustomerType0, false, "FLAT5", false, 20);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=568.43, quantity=20, customerType=REGULAR, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=20]", pricingEngine_PricingRequest0.toString());
      assertEquals(20, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(10234.73, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 1228, pricingEngine_CustomerType0, true, "save10", true, 1228);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=1228, customerType=VIP, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=1228]", pricingEngine_PricingRequest0.toString());
      assertEquals(1228, pricingEngine_PricingRequest0.quantity());
      assertEquals(1228, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
      assertEquals(980197.59, double0, 0.01);
      assertEquals(601, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1226.3, 10, pricingEngine_CustomerType0, false, "", false, 10);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=1226.3, quantity=10, customerType=VIP, seasonalSale=false, couponCode=, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(9573.13, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.valueOf("VIP");
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2193.4154424571, 2097, pricingEngine_CustomerType0, false, (String) null, true, 2759);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(3127730.67, double0, 0.01);
      assertEquals("PricingRequest[basePrice=2193.4154424571, quantity=2097, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=true, loyaltyPoints=2759]", pricingEngine_PricingRequest0.toString());
      assertEquals(2759, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 3014, pricingEngine_CustomerType0, false, "FREESHIP", true, 3014);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(3014, pricingEngine_PricingRequest0.quantity());
      assertEquals(3014, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=3014, customerType=VIP, seasonalSale=false, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=3014]", pricingEngine_PricingRequest0.toString());
      assertFalse(pricingEngine_PricingRequest0.seasonalSale());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1, pricingEngine_CustomerType0, false, "FLAT5", true, 20);
      assertEquals(1.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(20, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=REGULAR, seasonalSale=false, couponCode=FLAT5, firstOrder=true, loyaltyPoints=20]", pricingEngine_PricingRequest0.toString());
      assertEquals(8.94, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(3014, 3014, pricingEngine_CustomerType0, false, "FREESHIP", false, (-1619425278));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 316, (PricingEngine.CustomerType) null, false, "0[~[a1oW", false, 7448);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, (-6013), pricingEngine_CustomerType0, true, "FLAT5", false, (-932));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-2146979667), (-2146979667), pricingEngine_CustomerType0, false, "FREESHIP", false, (-2146979667));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      Object object0 = new Object();
      pricingEngine_PricingRequest0.equals(object0);
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", string0);
  }
}
