/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:11:29 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 0, pricingEngine_CustomerType0, true, "", true, 0);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.03, 1, pricingEngine_CustomerType0, false, "m\"zhYgx[", false, 1);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals(1, int0);
      assertEquals("PricingRequest[basePrice=0.03, quantity=1, customerType=REGULAR, seasonalSale=false, couponCode=m\"zhYgx[, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
      assertEquals(100, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1), pricingEngine_CustomerType0, true, "", true, 100);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=100.0, quantity=-1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 1228, pricingEngine_CustomerType0, true, "save10", true, 1228);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1228, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1228, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=0.0, quantity=1228, customerType=VIP, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=1228]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1, 1, pricingEngine_CustomerType0, true, "FLAT5", false, 786);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(8.67, double0, 0.01);
      assertEquals(786, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.1, 2482, pricingEngine_CustomerType0, false, "FLAT5", true, 2146203511);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(171.77, double0, 0.01);
      assertEquals("PricingRequest[basePrice=0.1, quantity=2482, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=true, loyaltyPoints=2146203511]", pricingEngine_PricingRequest0.toString());
      assertEquals(2146203511, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(980197.59, double0, 0.01);
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
      assertEquals(601, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.valueOf("VIP");
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2193.4154424571, 2097, pricingEngine_CustomerType0, false, (String) null, true, 2759);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2759, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(3127730.67, double0, 0.01);
      assertEquals("PricingRequest[basePrice=2193.4154424571, quantity=2097, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=true, loyaltyPoints=2759]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.05, 20, pricingEngine_CustomerType0, false, "", true, 20);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(20, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(8.84, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1, 1, pricingEngine_CustomerType0, true, "SAVE10", false, 0);
      assertEquals(1.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(8.72, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4179.99, 811, pricingEngine_CustomerType0, false, "com.viktor.lab4.PricingEngine$CustomerType", false, (-7091));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, (PricingEngine.CustomerType) null, false, (String) null, true, 477);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, (-6013), pricingEngine_CustomerType0, true, "FLAT5", false, (-932));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-2234.089832483), (-3005), pricingEngine_CustomerType0, false, (String) null, true, (-3005));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1228, 1228, pricingEngine_CustomerType0, true, "save10", true, 601);
      Object object0 = new Object();
      pricingEngine_PricingRequest0.equals(object0);
      assertEquals("PricingRequest[basePrice=1228.0, quantity=1228, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=601]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 1228, pricingEngine_CustomerType0, true, "FREESHIP", false, 477);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1228, pricingEngine_PricingRequest0.quantity());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals("PricingRequest[basePrice=0.0, quantity=1228, customerType=VIP, seasonalSale=true, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=477]", pricingEngine_PricingRequest0.toString());
      assertEquals(477, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2150, 2150, pricingEngine_CustomerType0, true, "mz-RTgx[", true, 2150);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=2150.0, quantity=2150, customerType=VIP, seasonalSale=true, couponCode=mz-RTgx[, firstOrder=true, loyaltyPoints=2150]", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }
}
