package com.viktor.lab4.autogen;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class RegressionTest1 {

    public static boolean debug = false;

    @Test
    public void test501() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test501");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache3 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj4 = new java.lang.Object();
        java.lang.Class<?> wildcardClass5 = obj4.getClass();
        java.lang.Object obj6 = new java.lang.Object();
        java.lang.Class<?> wildcardClass7 = obj6.getClass();
        typeLruCache3.put((java.lang.reflect.Type) wildcardClass5, (java.lang.invoke.TypeDescriptor) wildcardClass7);
        java.lang.invoke.TypeDescriptor typeDescriptor9 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass5);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache11 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj12 = new java.lang.Object();
        java.lang.Class<?> wildcardClass13 = obj12.getClass();
        java.lang.Object obj14 = new java.lang.Object();
        java.lang.Class<?> wildcardClass15 = obj14.getClass();
        typeLruCache11.put((java.lang.reflect.Type) wildcardClass13, (java.lang.invoke.TypeDescriptor) wildcardClass15);
        java.lang.invoke.TypeDescriptor typeDescriptor17 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass15);
        java.lang.reflect.Type type18 = null;
        java.lang.invoke.TypeDescriptor typeDescriptor19 = typeLruCache1.get(type18);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache21 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj22 = new java.lang.Object();
        java.lang.Class<?> wildcardClass23 = obj22.getClass();
        java.lang.Object obj24 = new java.lang.Object();
        java.lang.Class<?> wildcardClass25 = obj24.getClass();
        typeLruCache21.put((java.lang.reflect.Type) wildcardClass23, (java.lang.invoke.TypeDescriptor) wildcardClass25);
        java.lang.invoke.TypeDescriptor typeDescriptor27 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass23);
        com.viktor.lab4.LruCache<java.lang.constant.ConstantDesc, java.lang.String> constantDescLruCache29 = new com.viktor.lab4.LruCache<java.lang.constant.ConstantDesc, java.lang.String>((int) (short) 100);
        java.lang.Class<?> wildcardClass30 = constantDescLruCache29.getClass();
        boolean boolean31 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass30);
        int int32 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache34 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache36 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj37 = new java.lang.Object();
        java.lang.Class<?> wildcardClass38 = obj37.getClass();
        java.lang.Object obj39 = new java.lang.Object();
        java.lang.Class<?> wildcardClass40 = obj39.getClass();
        typeLruCache36.put((java.lang.reflect.Type) wildcardClass38, (java.lang.invoke.TypeDescriptor) wildcardClass40);
        java.lang.invoke.TypeDescriptor typeDescriptor42 = typeLruCache34.get((java.lang.reflect.Type) wildcardClass38);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache44 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj45 = new java.lang.Object();
        java.lang.Class<?> wildcardClass46 = obj45.getClass();
        java.lang.Object obj47 = new java.lang.Object();
        java.lang.Class<?> wildcardClass48 = obj47.getClass();
        typeLruCache44.put((java.lang.reflect.Type) wildcardClass46, (java.lang.invoke.TypeDescriptor) wildcardClass48);
        java.lang.invoke.TypeDescriptor typeDescriptor50 = typeLruCache34.get((java.lang.reflect.Type) wildcardClass48);
        java.lang.reflect.Type type51 = null;
        java.lang.invoke.TypeDescriptor typeDescriptor52 = typeLruCache34.get(type51);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache54 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache56 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj57 = new java.lang.Object();
        java.lang.Class<?> wildcardClass58 = obj57.getClass();
        java.lang.Object obj59 = new java.lang.Object();
        java.lang.Class<?> wildcardClass60 = obj59.getClass();
        typeLruCache56.put((java.lang.reflect.Type) wildcardClass58, (java.lang.invoke.TypeDescriptor) wildcardClass60);
        java.lang.Class<?> wildcardClass62 = typeLruCache56.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor63 = typeLruCache54.get((java.lang.reflect.Type) wildcardClass62);
        int int64 = typeLruCache54.size();
        java.lang.Class<?> wildcardClass65 = typeLruCache54.getClass();
        boolean boolean66 = typeLruCache34.containsKey((java.lang.reflect.Type) wildcardClass65);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache68 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj69 = new java.lang.Object();
        java.lang.Class<?> wildcardClass70 = obj69.getClass();
        java.lang.Object obj71 = new java.lang.Object();
        java.lang.Class<?> wildcardClass72 = obj71.getClass();
        typeLruCache68.put((java.lang.reflect.Type) wildcardClass70, (java.lang.invoke.TypeDescriptor) wildcardClass72);
        java.lang.Class<?> wildcardClass74 = typeLruCache68.getClass();
        boolean boolean75 = typeLruCache34.containsKey((java.lang.reflect.Type) wildcardClass74);
        java.lang.invoke.TypeDescriptor typeDescriptor76 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass74);
        // The following exception was thrown during execution in test generation
        try {
            java.lang.Class<?> wildcardClass77 = typeDescriptor76.getClass();
            org.junit.Assert.fail("Expected exception of type java.lang.NullPointerException; message: null");
        } catch (java.lang.NullPointerException e) {
            // Expected exception.
        }
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNotNull(wildcardClass7);
        org.junit.Assert.assertNull(typeDescriptor9);
        org.junit.Assert.assertNotNull(wildcardClass13);
        org.junit.Assert.assertNotNull(wildcardClass15);
        org.junit.Assert.assertNull(typeDescriptor17);
        org.junit.Assert.assertNull(typeDescriptor19);
        org.junit.Assert.assertNotNull(wildcardClass23);
        org.junit.Assert.assertNotNull(wildcardClass25);
        org.junit.Assert.assertNull(typeDescriptor27);
        org.junit.Assert.assertNotNull(wildcardClass30);
        org.junit.Assert.assertTrue("'" + boolean31 + "' != '" + false + "'", boolean31 == false);
        org.junit.Assert.assertTrue("'" + int32 + "' != '" + 0 + "'", int32 == 0);
        org.junit.Assert.assertNotNull(wildcardClass38);
        org.junit.Assert.assertNotNull(wildcardClass40);
        org.junit.Assert.assertNull(typeDescriptor42);
        org.junit.Assert.assertNotNull(wildcardClass46);
        org.junit.Assert.assertNotNull(wildcardClass48);
        org.junit.Assert.assertNull(typeDescriptor50);
        org.junit.Assert.assertNull(typeDescriptor52);
        org.junit.Assert.assertNotNull(wildcardClass58);
        org.junit.Assert.assertNotNull(wildcardClass60);
        org.junit.Assert.assertNotNull(wildcardClass62);
        org.junit.Assert.assertNull(typeDescriptor63);
        org.junit.Assert.assertTrue("'" + int64 + "' != '" + 0 + "'", int64 == 0);
        org.junit.Assert.assertNotNull(wildcardClass65);
        org.junit.Assert.assertTrue("'" + boolean66 + "' != '" + false + "'", boolean66 == false);
        org.junit.Assert.assertNotNull(wildcardClass70);
        org.junit.Assert.assertNotNull(wildcardClass72);
        org.junit.Assert.assertNotNull(wildcardClass74);
        org.junit.Assert.assertTrue("'" + boolean75 + "' != '" + false + "'", boolean75 == false);
        org.junit.Assert.assertNull(typeDescriptor76);
    }

    @Test
    public void test502() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test502");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache3 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(1);
        int int4 = typeLruCache3.size();
        int int5 = typeLruCache3.size();
        java.lang.Class<?> wildcardClass6 = typeLruCache3.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor7 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass6);
        java.lang.Class<?> wildcardClass8 = typeLruCache1.getClass();
        org.junit.Assert.assertTrue("'" + int4 + "' != '" + 0 + "'", int4 == 0);
        org.junit.Assert.assertTrue("'" + int5 + "' != '" + 0 + "'", int5 == 0);
        org.junit.Assert.assertNotNull(wildcardClass6);
        org.junit.Assert.assertNull(typeDescriptor7);
        org.junit.Assert.assertNotNull(wildcardClass8);
    }

    @Test
    public void test503() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test503");
        com.viktor.lab4.LruCache<java.lang.constant.Constable, com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>> constableLruCache1 = new com.viktor.lab4.LruCache<java.lang.constant.Constable, com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>>(10);
    }

    @Test
    public void test504() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test504");
        com.viktor.lab4.LruCache<com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>, java.lang.invoke.TypeDescriptor.OfField<java.lang.Class<?>>> typeLruCacheLruCache1 = new com.viktor.lab4.LruCache<com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>, java.lang.invoke.TypeDescriptor.OfField<java.lang.Class<?>>>(100);
        java.lang.Class<?> wildcardClass2 = typeLruCacheLruCache1.getClass();
        org.junit.Assert.assertNotNull(wildcardClass2);
    }

    @Test
    public void test505() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test505");
        com.viktor.lab4.LruCache<java.lang.Object, com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>> objLruCache1 = new com.viktor.lab4.LruCache<java.lang.Object, com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>>((int) '#');
    }

    @Test
    public void test506() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test506");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache3 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int4 = typeLruCache3.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache6 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache8 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache10 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj11 = new java.lang.Object();
        java.lang.Class<?> wildcardClass12 = obj11.getClass();
        java.lang.Object obj13 = new java.lang.Object();
        java.lang.Class<?> wildcardClass14 = obj13.getClass();
        typeLruCache10.put((java.lang.reflect.Type) wildcardClass12, (java.lang.invoke.TypeDescriptor) wildcardClass14);
        java.lang.invoke.TypeDescriptor typeDescriptor16 = typeLruCache8.get((java.lang.reflect.Type) wildcardClass12);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache18 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj19 = new java.lang.Object();
        java.lang.Class<?> wildcardClass20 = obj19.getClass();
        java.lang.Object obj21 = new java.lang.Object();
        java.lang.Class<?> wildcardClass22 = obj21.getClass();
        typeLruCache18.put((java.lang.reflect.Type) wildcardClass20, (java.lang.invoke.TypeDescriptor) wildcardClass22);
        java.lang.invoke.TypeDescriptor typeDescriptor24 = typeLruCache8.get((java.lang.reflect.Type) wildcardClass22);
        boolean boolean25 = typeLruCache6.containsKey((java.lang.reflect.Type) wildcardClass22);
        java.lang.reflect.Type type26 = null;
        java.lang.invoke.TypeDescriptor typeDescriptor27 = typeLruCache6.get(type26);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache29 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache31 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj32 = new java.lang.Object();
        java.lang.Class<?> wildcardClass33 = obj32.getClass();
        java.lang.Object obj34 = new java.lang.Object();
        java.lang.Class<?> wildcardClass35 = obj34.getClass();
        typeLruCache31.put((java.lang.reflect.Type) wildcardClass33, (java.lang.invoke.TypeDescriptor) wildcardClass35);
        java.lang.invoke.TypeDescriptor typeDescriptor37 = typeLruCache29.get((java.lang.reflect.Type) wildcardClass33);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache39 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj40 = new java.lang.Object();
        java.lang.Class<?> wildcardClass41 = obj40.getClass();
        java.lang.Object obj42 = new java.lang.Object();
        java.lang.Class<?> wildcardClass43 = obj42.getClass();
        typeLruCache39.put((java.lang.reflect.Type) wildcardClass41, (java.lang.invoke.TypeDescriptor) wildcardClass43);
        java.lang.invoke.TypeDescriptor typeDescriptor45 = typeLruCache29.get((java.lang.reflect.Type) wildcardClass43);
        boolean boolean46 = typeLruCache6.containsKey((java.lang.reflect.Type) wildcardClass43);
        com.viktor.lab4.LruCache<java.lang.constant.ConstantDesc, java.lang.String> constantDescLruCache48 = new com.viktor.lab4.LruCache<java.lang.constant.ConstantDesc, java.lang.String>((int) (short) 100);
        java.lang.Class<?> wildcardClass49 = constantDescLruCache48.getClass();
        typeLruCache3.put((java.lang.reflect.Type) wildcardClass43, (java.lang.invoke.TypeDescriptor) wildcardClass49);
        java.lang.invoke.TypeDescriptor typeDescriptor51 = null;
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass49, typeDescriptor51);
        int int53 = typeLruCache1.size();
        int int54 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache56 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache58 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj59 = new java.lang.Object();
        java.lang.Class<?> wildcardClass60 = obj59.getClass();
        java.lang.Object obj61 = new java.lang.Object();
        java.lang.Class<?> wildcardClass62 = obj61.getClass();
        typeLruCache58.put((java.lang.reflect.Type) wildcardClass60, (java.lang.invoke.TypeDescriptor) wildcardClass62);
        java.lang.Class<?> wildcardClass64 = typeLruCache58.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor65 = typeLruCache56.get((java.lang.reflect.Type) wildcardClass64);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache67 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache69 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache71 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj72 = new java.lang.Object();
        java.lang.Class<?> wildcardClass73 = obj72.getClass();
        java.lang.Object obj74 = new java.lang.Object();
        java.lang.Class<?> wildcardClass75 = obj74.getClass();
        typeLruCache71.put((java.lang.reflect.Type) wildcardClass73, (java.lang.invoke.TypeDescriptor) wildcardClass75);
        java.lang.invoke.TypeDescriptor typeDescriptor77 = typeLruCache69.get((java.lang.reflect.Type) wildcardClass73);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache79 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj80 = new java.lang.Object();
        java.lang.Class<?> wildcardClass81 = obj80.getClass();
        java.lang.Object obj82 = new java.lang.Object();
        java.lang.Class<?> wildcardClass83 = obj82.getClass();
        typeLruCache79.put((java.lang.reflect.Type) wildcardClass81, (java.lang.invoke.TypeDescriptor) wildcardClass83);
        java.lang.invoke.TypeDescriptor typeDescriptor85 = typeLruCache69.get((java.lang.reflect.Type) wildcardClass83);
        boolean boolean86 = typeLruCache67.containsKey((java.lang.reflect.Type) wildcardClass83);
        java.lang.Class<?> wildcardClass87 = typeLruCache67.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor88 = typeLruCache56.get((java.lang.reflect.Type) wildcardClass87);
        java.lang.Class<?> wildcardClass89 = typeLruCache56.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor90 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass89);
        org.junit.Assert.assertTrue("'" + int4 + "' != '" + 0 + "'", int4 == 0);
        org.junit.Assert.assertNotNull(wildcardClass12);
        org.junit.Assert.assertNotNull(wildcardClass14);
        org.junit.Assert.assertNull(typeDescriptor16);
        org.junit.Assert.assertNotNull(wildcardClass20);
        org.junit.Assert.assertNotNull(wildcardClass22);
        org.junit.Assert.assertNull(typeDescriptor24);
        org.junit.Assert.assertTrue("'" + boolean25 + "' != '" + false + "'", boolean25 == false);
        org.junit.Assert.assertNull(typeDescriptor27);
        org.junit.Assert.assertNotNull(wildcardClass33);
        org.junit.Assert.assertNotNull(wildcardClass35);
        org.junit.Assert.assertNull(typeDescriptor37);
        org.junit.Assert.assertNotNull(wildcardClass41);
        org.junit.Assert.assertNotNull(wildcardClass43);
        org.junit.Assert.assertNull(typeDescriptor45);
        org.junit.Assert.assertTrue("'" + boolean46 + "' != '" + false + "'", boolean46 == false);
        org.junit.Assert.assertNotNull(wildcardClass49);
        org.junit.Assert.assertTrue("'" + int53 + "' != '" + 1 + "'", int53 == 1);
        org.junit.Assert.assertTrue("'" + int54 + "' != '" + 1 + "'", int54 == 1);
        org.junit.Assert.assertNotNull(wildcardClass60);
        org.junit.Assert.assertNotNull(wildcardClass62);
        org.junit.Assert.assertNotNull(wildcardClass64);
        org.junit.Assert.assertNull(typeDescriptor65);
        org.junit.Assert.assertNotNull(wildcardClass73);
        org.junit.Assert.assertNotNull(wildcardClass75);
        org.junit.Assert.assertNull(typeDescriptor77);
        org.junit.Assert.assertNotNull(wildcardClass81);
        org.junit.Assert.assertNotNull(wildcardClass83);
        org.junit.Assert.assertNull(typeDescriptor85);
        org.junit.Assert.assertTrue("'" + boolean86 + "' != '" + false + "'", boolean86 == false);
        org.junit.Assert.assertNotNull(wildcardClass87);
        org.junit.Assert.assertNull(typeDescriptor88);
        org.junit.Assert.assertNotNull(wildcardClass89);
        org.junit.Assert.assertNull(typeDescriptor90);
    }

    @Test
    public void test507() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test507");
        com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.reflect.Type> wildcardClassLruCache1 = new com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.reflect.Type>((int) '4');
    }

    @Test
    public void test508() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test508");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache3 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj4 = new java.lang.Object();
        java.lang.Class<?> wildcardClass5 = obj4.getClass();
        java.lang.Object obj6 = new java.lang.Object();
        java.lang.Class<?> wildcardClass7 = obj6.getClass();
        typeLruCache3.put((java.lang.reflect.Type) wildcardClass5, (java.lang.invoke.TypeDescriptor) wildcardClass7);
        java.lang.Class<?> wildcardClass9 = typeLruCache3.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor10 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass9);
        int int11 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache13 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int14 = typeLruCache13.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache16 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass17 = typeLruCache16.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor18 = typeLruCache13.get((java.lang.reflect.Type) wildcardClass17);
        java.lang.invoke.TypeDescriptor typeDescriptor19 = null;
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass17, typeDescriptor19);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache22 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int23 = typeLruCache22.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache25 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj26 = new java.lang.Object();
        java.lang.Class<?> wildcardClass27 = obj26.getClass();
        java.lang.Object obj28 = new java.lang.Object();
        java.lang.Class<?> wildcardClass29 = obj28.getClass();
        typeLruCache25.put((java.lang.reflect.Type) wildcardClass27, (java.lang.invoke.TypeDescriptor) wildcardClass29);
        java.lang.Class<?> wildcardClass31 = typeLruCache25.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache33 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj34 = new java.lang.Object();
        java.lang.Class<?> wildcardClass35 = obj34.getClass();
        java.lang.Object obj36 = new java.lang.Object();
        java.lang.Class<?> wildcardClass37 = obj36.getClass();
        typeLruCache33.put((java.lang.reflect.Type) wildcardClass35, (java.lang.invoke.TypeDescriptor) wildcardClass37);
        typeLruCache22.put((java.lang.reflect.Type) wildcardClass31, (java.lang.invoke.TypeDescriptor) wildcardClass35);
        java.lang.invoke.TypeDescriptor typeDescriptor40 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass31);
        int int41 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache43 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(10);
        int int44 = typeLruCache43.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache46 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass47 = typeLruCache46.getClass();
        boolean boolean48 = typeLruCache43.containsKey((java.lang.reflect.Type) wildcardClass47);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache50 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(100);
        com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.String> wildcardClassLruCache52 = new com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.String>((int) ' ');
        java.lang.Class<?> wildcardClass53 = wildcardClassLruCache52.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor54 = typeLruCache50.get((java.lang.reflect.Type) wildcardClass53);
        java.lang.invoke.TypeDescriptor typeDescriptor55 = typeLruCache43.get((java.lang.reflect.Type) wildcardClass53);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache57 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj58 = new java.lang.Object();
        java.lang.Class<?> wildcardClass59 = obj58.getClass();
        java.lang.Object obj60 = new java.lang.Object();
        java.lang.Class<?> wildcardClass61 = obj60.getClass();
        typeLruCache57.put((java.lang.reflect.Type) wildcardClass59, (java.lang.invoke.TypeDescriptor) wildcardClass61);
        java.lang.Class<?> wildcardClass63 = typeLruCache57.getClass();
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass53, (java.lang.invoke.TypeDescriptor) wildcardClass63);
        int int65 = typeLruCache1.size();
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNotNull(wildcardClass7);
        org.junit.Assert.assertNotNull(wildcardClass9);
        org.junit.Assert.assertNull(typeDescriptor10);
        org.junit.Assert.assertTrue("'" + int11 + "' != '" + 0 + "'", int11 == 0);
        org.junit.Assert.assertTrue("'" + int14 + "' != '" + 0 + "'", int14 == 0);
        org.junit.Assert.assertNotNull(wildcardClass17);
        org.junit.Assert.assertNull(typeDescriptor18);
        org.junit.Assert.assertTrue("'" + int23 + "' != '" + 0 + "'", int23 == 0);
        org.junit.Assert.assertNotNull(wildcardClass27);
        org.junit.Assert.assertNotNull(wildcardClass29);
        org.junit.Assert.assertNotNull(wildcardClass31);
        org.junit.Assert.assertNotNull(wildcardClass35);
        org.junit.Assert.assertNotNull(wildcardClass37);
        org.junit.Assert.assertNull(typeDescriptor40);
        org.junit.Assert.assertTrue("'" + int41 + "' != '" + 1 + "'", int41 == 1);
        org.junit.Assert.assertTrue("'" + int44 + "' != '" + 0 + "'", int44 == 0);
        org.junit.Assert.assertNotNull(wildcardClass47);
        org.junit.Assert.assertTrue("'" + boolean48 + "' != '" + false + "'", boolean48 == false);
        org.junit.Assert.assertNotNull(wildcardClass53);
        org.junit.Assert.assertNull(typeDescriptor54);
        org.junit.Assert.assertNull(typeDescriptor55);
        org.junit.Assert.assertNotNull(wildcardClass59);
        org.junit.Assert.assertNotNull(wildcardClass61);
        org.junit.Assert.assertNotNull(wildcardClass63);
        org.junit.Assert.assertTrue("'" + int65 + "' != '" + 1 + "'", int65 == 1);
    }

    @Test
    public void test509() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test509");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int2 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache4 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass5 = typeLruCache4.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor6 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass5);
        int int7 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache9 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass10 = typeLruCache9.getClass();
        boolean boolean11 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass10);
        int int12 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache14 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache16 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj17 = new java.lang.Object();
        java.lang.Class<?> wildcardClass18 = obj17.getClass();
        java.lang.Object obj19 = new java.lang.Object();
        java.lang.Class<?> wildcardClass20 = obj19.getClass();
        typeLruCache16.put((java.lang.reflect.Type) wildcardClass18, (java.lang.invoke.TypeDescriptor) wildcardClass20);
        java.lang.Class<?> wildcardClass22 = typeLruCache16.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor23 = typeLruCache14.get((java.lang.reflect.Type) wildcardClass22);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache25 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj26 = new java.lang.Object();
        java.lang.Class<?> wildcardClass27 = obj26.getClass();
        java.lang.Object obj28 = new java.lang.Object();
        java.lang.Class<?> wildcardClass29 = obj28.getClass();
        typeLruCache25.put((java.lang.reflect.Type) wildcardClass27, (java.lang.invoke.TypeDescriptor) wildcardClass29);
        int int31 = typeLruCache25.size();
        java.lang.Class<?> wildcardClass32 = typeLruCache25.getClass();
        boolean boolean33 = typeLruCache14.containsKey((java.lang.reflect.Type) wildcardClass32);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache35 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) '#');
        java.lang.Class<?> wildcardClass36 = typeLruCache35.getClass();
        boolean boolean37 = typeLruCache14.containsKey((java.lang.reflect.Type) wildcardClass36);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache39 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(100);
        com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.String> wildcardClassLruCache41 = new com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.String>((int) ' ');
        java.lang.Class<?> wildcardClass42 = wildcardClassLruCache41.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor43 = typeLruCache39.get((java.lang.reflect.Type) wildcardClass42);
        com.viktor.lab4.LruCache<java.lang.constant.ConstantDesc, java.lang.String> constantDescLruCache45 = new com.viktor.lab4.LruCache<java.lang.constant.ConstantDesc, java.lang.String>((int) (short) 100);
        java.lang.Class<?> wildcardClass46 = constantDescLruCache45.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache48 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache50 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj51 = new java.lang.Object();
        java.lang.Class<?> wildcardClass52 = obj51.getClass();
        java.lang.Object obj53 = new java.lang.Object();
        java.lang.Class<?> wildcardClass54 = obj53.getClass();
        typeLruCache50.put((java.lang.reflect.Type) wildcardClass52, (java.lang.invoke.TypeDescriptor) wildcardClass54);
        java.lang.Class<?> wildcardClass56 = typeLruCache50.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor57 = typeLruCache48.get((java.lang.reflect.Type) wildcardClass56);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache59 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj60 = new java.lang.Object();
        java.lang.Class<?> wildcardClass61 = obj60.getClass();
        java.lang.Object obj62 = new java.lang.Object();
        java.lang.Class<?> wildcardClass63 = obj62.getClass();
        typeLruCache59.put((java.lang.reflect.Type) wildcardClass61, (java.lang.invoke.TypeDescriptor) wildcardClass63);
        int int65 = typeLruCache59.size();
        java.lang.Class<?> wildcardClass66 = typeLruCache59.getClass();
        boolean boolean67 = typeLruCache48.containsKey((java.lang.reflect.Type) wildcardClass66);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache69 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int70 = typeLruCache69.size();
        java.lang.Object obj71 = new java.lang.Object();
        java.lang.Class<?> wildcardClass72 = obj71.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache74 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass75 = typeLruCache74.getClass();
        typeLruCache69.put((java.lang.reflect.Type) wildcardClass72, (java.lang.invoke.TypeDescriptor) wildcardClass75);
        boolean boolean77 = typeLruCache48.containsKey((java.lang.reflect.Type) wildcardClass75);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache79 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(100);
        com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.String> wildcardClassLruCache81 = new com.viktor.lab4.LruCache<java.lang.Class<?>, java.lang.String>((int) ' ');
        java.lang.Class<?> wildcardClass82 = wildcardClassLruCache81.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor83 = typeLruCache79.get((java.lang.reflect.Type) wildcardClass82);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache85 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass86 = typeLruCache85.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor87 = typeLruCache79.get((java.lang.reflect.Type) wildcardClass86);
        java.lang.invoke.TypeDescriptor typeDescriptor88 = typeLruCache48.get((java.lang.reflect.Type) wildcardClass86);
        typeLruCache39.put((java.lang.reflect.Type) wildcardClass46, typeDescriptor88);
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass36, (java.lang.invoke.TypeDescriptor) wildcardClass46);
        org.junit.Assert.assertTrue("'" + int2 + "' != '" + 0 + "'", int2 == 0);
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNull(typeDescriptor6);
        org.junit.Assert.assertTrue("'" + int7 + "' != '" + 0 + "'", int7 == 0);
        org.junit.Assert.assertNotNull(wildcardClass10);
        org.junit.Assert.assertTrue("'" + boolean11 + "' != '" + false + "'", boolean11 == false);
        org.junit.Assert.assertTrue("'" + int12 + "' != '" + 0 + "'", int12 == 0);
        org.junit.Assert.assertNotNull(wildcardClass18);
        org.junit.Assert.assertNotNull(wildcardClass20);
        org.junit.Assert.assertNotNull(wildcardClass22);
        org.junit.Assert.assertNull(typeDescriptor23);
        org.junit.Assert.assertNotNull(wildcardClass27);
        org.junit.Assert.assertNotNull(wildcardClass29);
        org.junit.Assert.assertTrue("'" + int31 + "' != '" + 1 + "'", int31 == 1);
        org.junit.Assert.assertNotNull(wildcardClass32);
        org.junit.Assert.assertTrue("'" + boolean33 + "' != '" + false + "'", boolean33 == false);
        org.junit.Assert.assertNotNull(wildcardClass36);
        org.junit.Assert.assertTrue("'" + boolean37 + "' != '" + false + "'", boolean37 == false);
        org.junit.Assert.assertNotNull(wildcardClass42);
        org.junit.Assert.assertNull(typeDescriptor43);
        org.junit.Assert.assertNotNull(wildcardClass46);
        org.junit.Assert.assertNotNull(wildcardClass52);
        org.junit.Assert.assertNotNull(wildcardClass54);
        org.junit.Assert.assertNotNull(wildcardClass56);
        org.junit.Assert.assertNull(typeDescriptor57);
        org.junit.Assert.assertNotNull(wildcardClass61);
        org.junit.Assert.assertNotNull(wildcardClass63);
        org.junit.Assert.assertTrue("'" + int65 + "' != '" + 1 + "'", int65 == 1);
        org.junit.Assert.assertNotNull(wildcardClass66);
        org.junit.Assert.assertTrue("'" + boolean67 + "' != '" + false + "'", boolean67 == false);
        org.junit.Assert.assertTrue("'" + int70 + "' != '" + 0 + "'", int70 == 0);
        org.junit.Assert.assertNotNull(wildcardClass72);
        org.junit.Assert.assertNotNull(wildcardClass75);
        org.junit.Assert.assertTrue("'" + boolean77 + "' != '" + false + "'", boolean77 == false);
        org.junit.Assert.assertNotNull(wildcardClass82);
        org.junit.Assert.assertNull(typeDescriptor83);
        org.junit.Assert.assertNotNull(wildcardClass86);
        org.junit.Assert.assertNull(typeDescriptor87);
        org.junit.Assert.assertNull(typeDescriptor88);
    }

    @Test
    public void test510() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test510");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(1);
        int int2 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache4 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        java.lang.Class<?> wildcardClass5 = typeLruCache4.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache7 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj8 = new java.lang.Object();
        java.lang.Class<?> wildcardClass9 = obj8.getClass();
        java.lang.Object obj10 = new java.lang.Object();
        java.lang.Class<?> wildcardClass11 = obj10.getClass();
        typeLruCache7.put((java.lang.reflect.Type) wildcardClass9, (java.lang.invoke.TypeDescriptor) wildcardClass11);
        int int13 = typeLruCache7.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache15 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj16 = new java.lang.Object();
        java.lang.Class<?> wildcardClass17 = obj16.getClass();
        java.lang.Object obj18 = new java.lang.Object();
        java.lang.Class<?> wildcardClass19 = obj18.getClass();
        typeLruCache15.put((java.lang.reflect.Type) wildcardClass17, (java.lang.invoke.TypeDescriptor) wildcardClass19);
        int int21 = typeLruCache15.size();
        java.lang.Class<?> wildcardClass22 = typeLruCache15.getClass();
        boolean boolean23 = typeLruCache7.containsKey((java.lang.reflect.Type) wildcardClass22);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache25 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj26 = new java.lang.Object();
        java.lang.Class<?> wildcardClass27 = obj26.getClass();
        java.lang.Object obj28 = new java.lang.Object();
        java.lang.Class<?> wildcardClass29 = obj28.getClass();
        typeLruCache25.put((java.lang.reflect.Type) wildcardClass27, (java.lang.invoke.TypeDescriptor) wildcardClass29);
        int int31 = typeLruCache25.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache33 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj34 = new java.lang.Object();
        java.lang.Class<?> wildcardClass35 = obj34.getClass();
        java.lang.Object obj36 = new java.lang.Object();
        java.lang.Class<?> wildcardClass37 = obj36.getClass();
        typeLruCache33.put((java.lang.reflect.Type) wildcardClass35, (java.lang.invoke.TypeDescriptor) wildcardClass37);
        int int39 = typeLruCache33.size();
        java.lang.Class<?> wildcardClass40 = typeLruCache33.getClass();
        boolean boolean41 = typeLruCache25.containsKey((java.lang.reflect.Type) wildcardClass40);
        boolean boolean42 = typeLruCache7.containsKey((java.lang.reflect.Type) wildcardClass40);
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass5, (java.lang.invoke.TypeDescriptor) wildcardClass40);
        int int44 = typeLruCache1.size();
        int int45 = typeLruCache1.size();
        int int46 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.invoke.TypeDescriptor, java.io.Serializable> typeDescriptorLruCache48 = new com.viktor.lab4.LruCache<java.lang.invoke.TypeDescriptor, java.io.Serializable>((int) (short) 1);
        java.lang.Class<?> wildcardClass49 = typeDescriptorLruCache48.getClass();
        boolean boolean50 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass49);
        int int51 = typeLruCache1.size();
        java.lang.reflect.Type type52 = null;
        boolean boolean53 = typeLruCache1.containsKey(type52);
        java.lang.Class<?> wildcardClass54 = typeLruCache1.getClass();
        org.junit.Assert.assertTrue("'" + int2 + "' != '" + 0 + "'", int2 == 0);
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNotNull(wildcardClass9);
        org.junit.Assert.assertNotNull(wildcardClass11);
        org.junit.Assert.assertTrue("'" + int13 + "' != '" + 1 + "'", int13 == 1);
        org.junit.Assert.assertNotNull(wildcardClass17);
        org.junit.Assert.assertNotNull(wildcardClass19);
        org.junit.Assert.assertTrue("'" + int21 + "' != '" + 1 + "'", int21 == 1);
        org.junit.Assert.assertNotNull(wildcardClass22);
        org.junit.Assert.assertTrue("'" + boolean23 + "' != '" + false + "'", boolean23 == false);
        org.junit.Assert.assertNotNull(wildcardClass27);
        org.junit.Assert.assertNotNull(wildcardClass29);
        org.junit.Assert.assertTrue("'" + int31 + "' != '" + 1 + "'", int31 == 1);
        org.junit.Assert.assertNotNull(wildcardClass35);
        org.junit.Assert.assertNotNull(wildcardClass37);
        org.junit.Assert.assertTrue("'" + int39 + "' != '" + 1 + "'", int39 == 1);
        org.junit.Assert.assertNotNull(wildcardClass40);
        org.junit.Assert.assertTrue("'" + boolean41 + "' != '" + false + "'", boolean41 == false);
        org.junit.Assert.assertTrue("'" + boolean42 + "' != '" + false + "'", boolean42 == false);
        org.junit.Assert.assertTrue("'" + int44 + "' != '" + 1 + "'", int44 == 1);
        org.junit.Assert.assertTrue("'" + int45 + "' != '" + 1 + "'", int45 == 1);
        org.junit.Assert.assertTrue("'" + int46 + "' != '" + 1 + "'", int46 == 1);
        org.junit.Assert.assertNotNull(wildcardClass49);
        org.junit.Assert.assertTrue("'" + boolean50 + "' != '" + true + "'", boolean50 == true);
        org.junit.Assert.assertTrue("'" + int51 + "' != '" + 1 + "'", int51 == 1);
        org.junit.Assert.assertTrue("'" + boolean53 + "' != '" + false + "'", boolean53 == false);
        org.junit.Assert.assertNotNull(wildcardClass54);
    }

    @Test
    public void test511() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test511");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache3 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj4 = new java.lang.Object();
        java.lang.Class<?> wildcardClass5 = obj4.getClass();
        java.lang.Object obj6 = new java.lang.Object();
        java.lang.Class<?> wildcardClass7 = obj6.getClass();
        typeLruCache3.put((java.lang.reflect.Type) wildcardClass5, (java.lang.invoke.TypeDescriptor) wildcardClass7);
        java.lang.invoke.TypeDescriptor typeDescriptor9 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass5);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache11 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj12 = new java.lang.Object();
        java.lang.Class<?> wildcardClass13 = obj12.getClass();
        java.lang.Object obj14 = new java.lang.Object();
        java.lang.Class<?> wildcardClass15 = obj14.getClass();
        typeLruCache11.put((java.lang.reflect.Type) wildcardClass13, (java.lang.invoke.TypeDescriptor) wildcardClass15);
        java.lang.invoke.TypeDescriptor typeDescriptor17 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass15);
        java.lang.reflect.Type type18 = null;
        java.lang.invoke.TypeDescriptor typeDescriptor19 = typeLruCache1.get(type18);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache21 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj22 = new java.lang.Object();
        java.lang.Class<?> wildcardClass23 = obj22.getClass();
        java.lang.Object obj24 = new java.lang.Object();
        java.lang.Class<?> wildcardClass25 = obj24.getClass();
        typeLruCache21.put((java.lang.reflect.Type) wildcardClass23, (java.lang.invoke.TypeDescriptor) wildcardClass25);
        java.lang.invoke.TypeDescriptor typeDescriptor27 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass23);
        int int28 = typeLruCache1.size();
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNotNull(wildcardClass7);
        org.junit.Assert.assertNull(typeDescriptor9);
        org.junit.Assert.assertNotNull(wildcardClass13);
        org.junit.Assert.assertNotNull(wildcardClass15);
        org.junit.Assert.assertNull(typeDescriptor17);
        org.junit.Assert.assertNull(typeDescriptor19);
        org.junit.Assert.assertNotNull(wildcardClass23);
        org.junit.Assert.assertNotNull(wildcardClass25);
        org.junit.Assert.assertNull(typeDescriptor27);
        org.junit.Assert.assertTrue("'" + int28 + "' != '" + 0 + "'", int28 == 0);
    }

    @Test
    public void test512() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test512");
        com.viktor.lab4.LruCache<java.lang.reflect.AnnotatedElement, java.lang.reflect.Type> annotatedElementLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.AnnotatedElement, java.lang.reflect.Type>((int) (short) 100);
    }

    @Test
    public void test513() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test513");
        com.viktor.lab4.LruCache<java.io.Serializable, com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>> serializableLruCache1 = new com.viktor.lab4.LruCache<java.io.Serializable, com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>>((int) 'a');
        java.lang.Class<?> wildcardClass2 = serializableLruCache1.getClass();
        org.junit.Assert.assertNotNull(wildcardClass2);
    }

    @Test
    public void test514() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test514");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(10);
        int int2 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache4 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>(1);
        int int5 = typeLruCache4.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache7 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        java.lang.Class<?> wildcardClass8 = typeLruCache7.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache10 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj11 = new java.lang.Object();
        java.lang.Class<?> wildcardClass12 = obj11.getClass();
        java.lang.Object obj13 = new java.lang.Object();
        java.lang.Class<?> wildcardClass14 = obj13.getClass();
        typeLruCache10.put((java.lang.reflect.Type) wildcardClass12, (java.lang.invoke.TypeDescriptor) wildcardClass14);
        int int16 = typeLruCache10.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache18 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj19 = new java.lang.Object();
        java.lang.Class<?> wildcardClass20 = obj19.getClass();
        java.lang.Object obj21 = new java.lang.Object();
        java.lang.Class<?> wildcardClass22 = obj21.getClass();
        typeLruCache18.put((java.lang.reflect.Type) wildcardClass20, (java.lang.invoke.TypeDescriptor) wildcardClass22);
        int int24 = typeLruCache18.size();
        java.lang.Class<?> wildcardClass25 = typeLruCache18.getClass();
        boolean boolean26 = typeLruCache10.containsKey((java.lang.reflect.Type) wildcardClass25);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache28 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj29 = new java.lang.Object();
        java.lang.Class<?> wildcardClass30 = obj29.getClass();
        java.lang.Object obj31 = new java.lang.Object();
        java.lang.Class<?> wildcardClass32 = obj31.getClass();
        typeLruCache28.put((java.lang.reflect.Type) wildcardClass30, (java.lang.invoke.TypeDescriptor) wildcardClass32);
        int int34 = typeLruCache28.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache36 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj37 = new java.lang.Object();
        java.lang.Class<?> wildcardClass38 = obj37.getClass();
        java.lang.Object obj39 = new java.lang.Object();
        java.lang.Class<?> wildcardClass40 = obj39.getClass();
        typeLruCache36.put((java.lang.reflect.Type) wildcardClass38, (java.lang.invoke.TypeDescriptor) wildcardClass40);
        int int42 = typeLruCache36.size();
        java.lang.Class<?> wildcardClass43 = typeLruCache36.getClass();
        boolean boolean44 = typeLruCache28.containsKey((java.lang.reflect.Type) wildcardClass43);
        boolean boolean45 = typeLruCache10.containsKey((java.lang.reflect.Type) wildcardClass43);
        typeLruCache4.put((java.lang.reflect.Type) wildcardClass8, (java.lang.invoke.TypeDescriptor) wildcardClass43);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache48 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int49 = typeLruCache48.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache51 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj52 = new java.lang.Object();
        java.lang.Class<?> wildcardClass53 = obj52.getClass();
        java.lang.Object obj54 = new java.lang.Object();
        java.lang.Class<?> wildcardClass55 = obj54.getClass();
        typeLruCache51.put((java.lang.reflect.Type) wildcardClass53, (java.lang.invoke.TypeDescriptor) wildcardClass55);
        java.lang.Class<?> wildcardClass57 = typeLruCache51.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache59 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj60 = new java.lang.Object();
        java.lang.Class<?> wildcardClass61 = obj60.getClass();
        java.lang.Object obj62 = new java.lang.Object();
        java.lang.Class<?> wildcardClass63 = obj62.getClass();
        typeLruCache59.put((java.lang.reflect.Type) wildcardClass61, (java.lang.invoke.TypeDescriptor) wildcardClass63);
        typeLruCache48.put((java.lang.reflect.Type) wildcardClass57, (java.lang.invoke.TypeDescriptor) wildcardClass61);
        boolean boolean66 = typeLruCache4.containsKey((java.lang.reflect.Type) wildcardClass61);
        int int67 = typeLruCache4.size();
        java.lang.Class<?> wildcardClass68 = typeLruCache4.getClass();
        boolean boolean69 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass68);
        org.junit.Assert.assertTrue("'" + int2 + "' != '" + 0 + "'", int2 == 0);
        org.junit.Assert.assertTrue("'" + int5 + "' != '" + 0 + "'", int5 == 0);
        org.junit.Assert.assertNotNull(wildcardClass8);
        org.junit.Assert.assertNotNull(wildcardClass12);
        org.junit.Assert.assertNotNull(wildcardClass14);
        org.junit.Assert.assertTrue("'" + int16 + "' != '" + 1 + "'", int16 == 1);
        org.junit.Assert.assertNotNull(wildcardClass20);
        org.junit.Assert.assertNotNull(wildcardClass22);
        org.junit.Assert.assertTrue("'" + int24 + "' != '" + 1 + "'", int24 == 1);
        org.junit.Assert.assertNotNull(wildcardClass25);
        org.junit.Assert.assertTrue("'" + boolean26 + "' != '" + false + "'", boolean26 == false);
        org.junit.Assert.assertNotNull(wildcardClass30);
        org.junit.Assert.assertNotNull(wildcardClass32);
        org.junit.Assert.assertTrue("'" + int34 + "' != '" + 1 + "'", int34 == 1);
        org.junit.Assert.assertNotNull(wildcardClass38);
        org.junit.Assert.assertNotNull(wildcardClass40);
        org.junit.Assert.assertTrue("'" + int42 + "' != '" + 1 + "'", int42 == 1);
        org.junit.Assert.assertNotNull(wildcardClass43);
        org.junit.Assert.assertTrue("'" + boolean44 + "' != '" + false + "'", boolean44 == false);
        org.junit.Assert.assertTrue("'" + boolean45 + "' != '" + false + "'", boolean45 == false);
        org.junit.Assert.assertTrue("'" + int49 + "' != '" + 0 + "'", int49 == 0);
        org.junit.Assert.assertNotNull(wildcardClass53);
        org.junit.Assert.assertNotNull(wildcardClass55);
        org.junit.Assert.assertNotNull(wildcardClass57);
        org.junit.Assert.assertNotNull(wildcardClass61);
        org.junit.Assert.assertNotNull(wildcardClass63);
        org.junit.Assert.assertTrue("'" + boolean66 + "' != '" + false + "'", boolean66 == false);
        org.junit.Assert.assertTrue("'" + int67 + "' != '" + 1 + "'", int67 == 1);
        org.junit.Assert.assertNotNull(wildcardClass68);
        org.junit.Assert.assertTrue("'" + boolean69 + "' != '" + false + "'", boolean69 == false);
    }

    @Test
    public void test515() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test515");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache3 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj4 = new java.lang.Object();
        java.lang.Class<?> wildcardClass5 = obj4.getClass();
        java.lang.Object obj6 = new java.lang.Object();
        java.lang.Class<?> wildcardClass7 = obj6.getClass();
        typeLruCache3.put((java.lang.reflect.Type) wildcardClass5, (java.lang.invoke.TypeDescriptor) wildcardClass7);
        java.lang.invoke.TypeDescriptor typeDescriptor9 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass5);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache11 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj12 = new java.lang.Object();
        java.lang.Class<?> wildcardClass13 = obj12.getClass();
        java.lang.Object obj14 = new java.lang.Object();
        java.lang.Class<?> wildcardClass15 = obj14.getClass();
        typeLruCache11.put((java.lang.reflect.Type) wildcardClass13, (java.lang.invoke.TypeDescriptor) wildcardClass15);
        java.lang.invoke.TypeDescriptor typeDescriptor17 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass15);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache19 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj20 = new java.lang.Object();
        java.lang.Class<?> wildcardClass21 = obj20.getClass();
        java.lang.Object obj22 = new java.lang.Object();
        java.lang.Class<?> wildcardClass23 = obj22.getClass();
        typeLruCache19.put((java.lang.reflect.Type) wildcardClass21, (java.lang.invoke.TypeDescriptor) wildcardClass23);
        int int25 = typeLruCache19.size();
        java.lang.Class<?> wildcardClass26 = typeLruCache19.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache28 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache30 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj31 = new java.lang.Object();
        java.lang.Class<?> wildcardClass32 = obj31.getClass();
        java.lang.Object obj33 = new java.lang.Object();
        java.lang.Class<?> wildcardClass34 = obj33.getClass();
        typeLruCache30.put((java.lang.reflect.Type) wildcardClass32, (java.lang.invoke.TypeDescriptor) wildcardClass34);
        java.lang.Class<?> wildcardClass36 = typeLruCache30.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor37 = typeLruCache28.get((java.lang.reflect.Type) wildcardClass36);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache39 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache41 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj42 = new java.lang.Object();
        java.lang.Class<?> wildcardClass43 = obj42.getClass();
        java.lang.Object obj44 = new java.lang.Object();
        java.lang.Class<?> wildcardClass45 = obj44.getClass();
        typeLruCache41.put((java.lang.reflect.Type) wildcardClass43, (java.lang.invoke.TypeDescriptor) wildcardClass45);
        java.lang.Class<?> wildcardClass47 = typeLruCache41.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor48 = typeLruCache39.get((java.lang.reflect.Type) wildcardClass47);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache50 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache52 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj53 = new java.lang.Object();
        java.lang.Class<?> wildcardClass54 = obj53.getClass();
        java.lang.Object obj55 = new java.lang.Object();
        java.lang.Class<?> wildcardClass56 = obj55.getClass();
        typeLruCache52.put((java.lang.reflect.Type) wildcardClass54, (java.lang.invoke.TypeDescriptor) wildcardClass56);
        java.lang.invoke.TypeDescriptor typeDescriptor58 = typeLruCache50.get((java.lang.reflect.Type) wildcardClass54);
        java.lang.invoke.TypeDescriptor typeDescriptor59 = typeLruCache39.get((java.lang.reflect.Type) wildcardClass54);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache61 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache63 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj64 = new java.lang.Object();
        java.lang.Class<?> wildcardClass65 = obj64.getClass();
        java.lang.Object obj66 = new java.lang.Object();
        java.lang.Class<?> wildcardClass67 = obj66.getClass();
        typeLruCache63.put((java.lang.reflect.Type) wildcardClass65, (java.lang.invoke.TypeDescriptor) wildcardClass67);
        java.lang.Class<?> wildcardClass69 = typeLruCache63.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor70 = typeLruCache61.get((java.lang.reflect.Type) wildcardClass69);
        int int71 = typeLruCache61.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache73 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        java.lang.Class<?> wildcardClass74 = typeLruCache73.getClass();
        boolean boolean75 = typeLruCache61.containsKey((java.lang.reflect.Type) wildcardClass74);
        typeLruCache28.put((java.lang.reflect.Type) wildcardClass54, (java.lang.invoke.TypeDescriptor) wildcardClass74);
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass26, (java.lang.invoke.TypeDescriptor) wildcardClass54);
        int int78 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.String, java.lang.reflect.GenericDeclaration> strLruCache80 = new com.viktor.lab4.LruCache<java.lang.String, java.lang.reflect.GenericDeclaration>((int) (byte) 1);
        java.lang.Class<?> wildcardClass81 = strLruCache80.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor82 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass81);
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNotNull(wildcardClass7);
        org.junit.Assert.assertNull(typeDescriptor9);
        org.junit.Assert.assertNotNull(wildcardClass13);
        org.junit.Assert.assertNotNull(wildcardClass15);
        org.junit.Assert.assertNull(typeDescriptor17);
        org.junit.Assert.assertNotNull(wildcardClass21);
        org.junit.Assert.assertNotNull(wildcardClass23);
        org.junit.Assert.assertTrue("'" + int25 + "' != '" + 1 + "'", int25 == 1);
        org.junit.Assert.assertNotNull(wildcardClass26);
        org.junit.Assert.assertNotNull(wildcardClass32);
        org.junit.Assert.assertNotNull(wildcardClass34);
        org.junit.Assert.assertNotNull(wildcardClass36);
        org.junit.Assert.assertNull(typeDescriptor37);
        org.junit.Assert.assertNotNull(wildcardClass43);
        org.junit.Assert.assertNotNull(wildcardClass45);
        org.junit.Assert.assertNotNull(wildcardClass47);
        org.junit.Assert.assertNull(typeDescriptor48);
        org.junit.Assert.assertNotNull(wildcardClass54);
        org.junit.Assert.assertNotNull(wildcardClass56);
        org.junit.Assert.assertNull(typeDescriptor58);
        org.junit.Assert.assertNull(typeDescriptor59);
        org.junit.Assert.assertNotNull(wildcardClass65);
        org.junit.Assert.assertNotNull(wildcardClass67);
        org.junit.Assert.assertNotNull(wildcardClass69);
        org.junit.Assert.assertNull(typeDescriptor70);
        org.junit.Assert.assertTrue("'" + int71 + "' != '" + 0 + "'", int71 == 0);
        org.junit.Assert.assertNotNull(wildcardClass74);
        org.junit.Assert.assertTrue("'" + boolean75 + "' != '" + false + "'", boolean75 == false);
        org.junit.Assert.assertTrue("'" + int78 + "' != '" + 1 + "'", int78 == 1);
        org.junit.Assert.assertNotNull(wildcardClass81);
        org.junit.Assert.assertNotNull(typeDescriptor82);
    }

    @Test
    public void test516() throws Throwable {
        if (debug)
            System.out.format("%n%s%n", "RegressionTest1.test516");
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache1 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int2 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache4 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass5 = typeLruCache4.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor6 = typeLruCache1.get((java.lang.reflect.Type) wildcardClass5);
        int int7 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache9 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Class<?> wildcardClass10 = typeLruCache9.getClass();
        boolean boolean11 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass10);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache13 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj14 = new java.lang.Object();
        java.lang.Class<?> wildcardClass15 = obj14.getClass();
        java.lang.Object obj16 = new java.lang.Object();
        java.lang.Class<?> wildcardClass17 = obj16.getClass();
        typeLruCache13.put((java.lang.reflect.Type) wildcardClass15, (java.lang.invoke.TypeDescriptor) wildcardClass17);
        int int19 = typeLruCache13.size();
        int int20 = typeLruCache13.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache22 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj23 = new java.lang.Object();
        java.lang.Class<?> wildcardClass24 = obj23.getClass();
        java.lang.Object obj25 = new java.lang.Object();
        java.lang.Class<?> wildcardClass26 = obj25.getClass();
        typeLruCache22.put((java.lang.reflect.Type) wildcardClass24, (java.lang.invoke.TypeDescriptor) wildcardClass26);
        boolean boolean28 = typeLruCache13.containsKey((java.lang.reflect.Type) wildcardClass24);
        int int29 = typeLruCache13.size();
        int int30 = typeLruCache13.size();
        java.lang.Class<?> wildcardClass31 = typeLruCache13.getClass();
        boolean boolean32 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass31);
        int int33 = typeLruCache1.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache35 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache37 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache39 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj40 = new java.lang.Object();
        java.lang.Class<?> wildcardClass41 = obj40.getClass();
        java.lang.Object obj42 = new java.lang.Object();
        java.lang.Class<?> wildcardClass43 = obj42.getClass();
        typeLruCache39.put((java.lang.reflect.Type) wildcardClass41, (java.lang.invoke.TypeDescriptor) wildcardClass43);
        java.lang.invoke.TypeDescriptor typeDescriptor45 = typeLruCache37.get((java.lang.reflect.Type) wildcardClass41);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache47 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj48 = new java.lang.Object();
        java.lang.Class<?> wildcardClass49 = obj48.getClass();
        java.lang.Object obj50 = new java.lang.Object();
        java.lang.Class<?> wildcardClass51 = obj50.getClass();
        typeLruCache47.put((java.lang.reflect.Type) wildcardClass49, (java.lang.invoke.TypeDescriptor) wildcardClass51);
        java.lang.invoke.TypeDescriptor typeDescriptor53 = typeLruCache37.get((java.lang.reflect.Type) wildcardClass51);
        boolean boolean54 = typeLruCache35.containsKey((java.lang.reflect.Type) wildcardClass51);
        java.lang.reflect.Type type55 = null;
        java.lang.invoke.TypeDescriptor typeDescriptor56 = typeLruCache35.get(type55);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache58 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int59 = typeLruCache58.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache61 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj62 = new java.lang.Object();
        java.lang.Class<?> wildcardClass63 = obj62.getClass();
        java.lang.Object obj64 = new java.lang.Object();
        java.lang.Class<?> wildcardClass65 = obj64.getClass();
        typeLruCache61.put((java.lang.reflect.Type) wildcardClass63, (java.lang.invoke.TypeDescriptor) wildcardClass65);
        java.lang.Class<?> wildcardClass67 = typeLruCache61.getClass();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache69 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj70 = new java.lang.Object();
        java.lang.Class<?> wildcardClass71 = obj70.getClass();
        java.lang.Object obj72 = new java.lang.Object();
        java.lang.Class<?> wildcardClass73 = obj72.getClass();
        typeLruCache69.put((java.lang.reflect.Type) wildcardClass71, (java.lang.invoke.TypeDescriptor) wildcardClass73);
        typeLruCache58.put((java.lang.reflect.Type) wildcardClass67, (java.lang.invoke.TypeDescriptor) wildcardClass71);
        java.lang.invoke.TypeDescriptor typeDescriptor76 = typeLruCache35.get((java.lang.reflect.Type) wildcardClass71);
        java.lang.Class<?> wildcardClass77 = typeLruCache35.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor78 = null;
        typeLruCache1.put((java.lang.reflect.Type) wildcardClass77, typeDescriptor78);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache81 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        int int82 = typeLruCache81.size();
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache84 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 1);
        com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor> typeLruCache86 = new com.viktor.lab4.LruCache<java.lang.reflect.Type, java.lang.invoke.TypeDescriptor>((int) (short) 100);
        java.lang.Object obj87 = new java.lang.Object();
        java.lang.Class<?> wildcardClass88 = obj87.getClass();
        java.lang.Object obj89 = new java.lang.Object();
        java.lang.Class<?> wildcardClass90 = obj89.getClass();
        typeLruCache86.put((java.lang.reflect.Type) wildcardClass88, (java.lang.invoke.TypeDescriptor) wildcardClass90);
        java.lang.Class<?> wildcardClass92 = typeLruCache86.getClass();
        java.lang.invoke.TypeDescriptor typeDescriptor93 = typeLruCache84.get((java.lang.reflect.Type) wildcardClass92);
        boolean boolean94 = typeLruCache81.containsKey((java.lang.reflect.Type) wildcardClass92);
        java.lang.Class<?> wildcardClass95 = typeLruCache81.getClass();
        boolean boolean96 = typeLruCache1.containsKey((java.lang.reflect.Type) wildcardClass95);
        java.lang.reflect.Type type97 = null;
        boolean boolean98 = typeLruCache1.containsKey(type97);
        int int99 = typeLruCache1.size();
        org.junit.Assert.assertTrue("'" + int2 + "' != '" + 0 + "'", int2 == 0);
        org.junit.Assert.assertNotNull(wildcardClass5);
        org.junit.Assert.assertNull(typeDescriptor6);
        org.junit.Assert.assertTrue("'" + int7 + "' != '" + 0 + "'", int7 == 0);
        org.junit.Assert.assertNotNull(wildcardClass10);
        org.junit.Assert.assertTrue("'" + boolean11 + "' != '" + false + "'", boolean11 == false);
        org.junit.Assert.assertNotNull(wildcardClass15);
        org.junit.Assert.assertNotNull(wildcardClass17);
        org.junit.Assert.assertTrue("'" + int19 + "' != '" + 1 + "'", int19 == 1);
        org.junit.Assert.assertTrue("'" + int20 + "' != '" + 1 + "'", int20 == 1);
        org.junit.Assert.assertNotNull(wildcardClass24);
        org.junit.Assert.assertNotNull(wildcardClass26);
        org.junit.Assert.assertTrue("'" + boolean28 + "' != '" + true + "'", boolean28 == true);
        org.junit.Assert.assertTrue("'" + int29 + "' != '" + 1 + "'", int29 == 1);
        org.junit.Assert.assertTrue("'" + int30 + "' != '" + 1 + "'", int30 == 1);
        org.junit.Assert.assertNotNull(wildcardClass31);
        org.junit.Assert.assertTrue("'" + boolean32 + "' != '" + false + "'", boolean32 == false);
        org.junit.Assert.assertTrue("'" + int33 + "' != '" + 0 + "'", int33 == 0);
        org.junit.Assert.assertNotNull(wildcardClass41);
        org.junit.Assert.assertNotNull(wildcardClass43);
        org.junit.Assert.assertNull(typeDescriptor45);
        org.junit.Assert.assertNotNull(wildcardClass49);
        org.junit.Assert.assertNotNull(wildcardClass51);
        org.junit.Assert.assertNull(typeDescriptor53);
        org.junit.Assert.assertTrue("'" + boolean54 + "' != '" + false + "'", boolean54 == false);
        org.junit.Assert.assertNull(typeDescriptor56);
        org.junit.Assert.assertTrue("'" + int59 + "' != '" + 0 + "'", int59 == 0);
        org.junit.Assert.assertNotNull(wildcardClass63);
        org.junit.Assert.assertNotNull(wildcardClass65);
        org.junit.Assert.assertNotNull(wildcardClass67);
        org.junit.Assert.assertNotNull(wildcardClass71);
        org.junit.Assert.assertNotNull(wildcardClass73);
        org.junit.Assert.assertNull(typeDescriptor76);
        org.junit.Assert.assertNotNull(wildcardClass77);
        org.junit.Assert.assertTrue("'" + int82 + "' != '" + 0 + "'", int82 == 0);
        org.junit.Assert.assertNotNull(wildcardClass88);
        org.junit.Assert.assertNotNull(wildcardClass90);
        org.junit.Assert.assertNotNull(wildcardClass92);
        org.junit.Assert.assertNull(typeDescriptor93);
        org.junit.Assert.assertTrue("'" + boolean94 + "' != '" + false + "'", boolean94 == false);
        org.junit.Assert.assertNotNull(wildcardClass95);
        org.junit.Assert.assertTrue("'" + boolean96 + "' != '" + true + "'", boolean96 == true);
        org.junit.Assert.assertTrue("'" + boolean98 + "' != '" + false + "'", boolean98 == false);
        org.junit.Assert.assertTrue("'" + int99 + "' != '" + 1 + "'", int99 == 1);
    }
}

