/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:01:23 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.SimpleJsonParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleJsonParser_ESTest extends SimpleJsonParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[5dO;tYgdOO_");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got 'd' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("5n.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[zE)y{4*]2");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token 'z' at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("!J j#0y/y=s!'d)d");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token '!' at position 0
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"Dh+Xs`[ y-}m");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated string literal at position 13
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("3 Sw;}Z#3^cg");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[]qU:fIFuM");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("2.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected end of input at position 0
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      Object object0 = simpleJsonParser0.parse("04");
      assertEquals(4.0, object0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input must not be null
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\">\".i0l|EJg");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[7(Q=-?=eLig]dX5");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got '(' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }
}
