/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:12:24 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(892.64, (-685), pricingEngine_CustomerType0, false, "", false, 10);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, (String) null, false, 10);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, (String) null, false, 10);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals(10, int0);
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(3926.4219943, 10, pricingEngine_CustomerType0, false, "FREESHIP", false, 10);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals(10, int0);
      assertEquals("PricingRequest[basePrice=3926.4219943, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(3926.4219943, 10, pricingEngine_CustomerType0, false, "FREESHIP", false, 10);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=3926.4219943, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, (String) null, false, 10);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.1, 10, pricingEngine_CustomerType0, false, "RhK?0]>Lp)*%{P~", false, 10);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=0.1, quantity=10, customerType=VIP, seasonalSale=false, couponCode=RhK?0]>Lp)*%{P~, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(3926.4219943, 10, pricingEngine_CustomerType0, false, "FREESHIP", false, 10);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=3926.4219943, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 53, pricingEngine_CustomerType0, true, "FREESHIP", true, 43);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=53, customerType=VIP, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=43]", pricingEngine_PricingRequest0.toString());
      assertEquals(53, pricingEngine_PricingRequest0.quantity());
      assertEquals(43, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(170.6602079944, 53, pricingEngine_CustomerType0, false, "SAVE10", false, 53);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(53, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=170.6602079944, quantity=53, customerType=VIP, seasonalSale=false, couponCode=SAVE10, firstOrder=false, loyaltyPoints=53]", pricingEngine_PricingRequest0.toString());
      assertEquals(5887.23, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(26, 26, pricingEngine_CustomerType0, false, "FREESHIP", false, 26);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(26, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(608.4, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.1, 198, pricingEngine_CustomerType0, true, "SAVE10", true, 198);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(198, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(21.65, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(38, 38, pricingEngine_CustomerType0, true, "", true, 38);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(38, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1018.79, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(62, 62, pricingEngine_CustomerType0, false, (String) null, true, 62);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(62, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(2814.11, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(15692.1203, 5, pricingEngine_CustomerType0, false, "FLAT5", false, 5);
      assertEquals(15692.1203, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=15692.1203, quantity=5, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=5]", pricingEngine_PricingRequest0.toString());
      assertEquals(5, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(69048.32, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(43, 43, pricingEngine_CustomerType0, false, "E_7YRZ\"=,+(O", false, (-1));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5, 0, pricingEngine_CustomerType0, false, "`z^ k(<LVhpJ", true, 0);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-1), (-1), pricingEngine_CustomerType0, true, "", true, (-1));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5, 0, pricingEngine_CustomerType0, false, "`z^ k(<LVhpJ", true, 0);
      pricingEngine_PricingRequest0.equals("save10");
      assertEquals("PricingRequest[basePrice=5.0, quantity=0, customerType=VIP, seasonalSale=false, couponCode=`z^ k(<LVhpJ, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(3926.4219943, 10, pricingEngine_CustomerType0, false, "FREESHIP", false, 10);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=3926.4219943, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=10]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 53, pricingEngine_CustomerType0, true, "FLAT5", false, 0);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(53, pricingEngine_PricingRequest0.quantity());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals("PricingRequest[basePrice=0.0, quantity=53, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertFalse(pricingEngine_PricingRequest0.firstOrder());
  }
}
