/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 17:37:42 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.LongestIncreasingSubsequence;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LongestIncreasingSubsequence_ESTest extends LongestIncreasingSubsequence_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LongestIncreasingSubsequence longestIncreasingSubsequence0 = new LongestIncreasingSubsequence();
      int[] intArray0 = new int[7];
      intArray0[2] = (-1);
      int int0 = longestIncreasingSubsequence0.lengthOfLIS(intArray0);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LongestIncreasingSubsequence longestIncreasingSubsequence0 = new LongestIncreasingSubsequence();
      int[] intArray0 = new int[0];
      int int0 = longestIncreasingSubsequence0.lengthOfLIS(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LongestIncreasingSubsequence longestIncreasingSubsequence0 = new LongestIncreasingSubsequence();
      // Undeclared exception!
      try { 
        longestIncreasingSubsequence0.lengthOfLIS((int[]) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // numbers must not be null
         //
         verifyException("com.viktor.lab4.LongestIncreasingSubsequence", e);
      }
  }
}
