/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 17:42:03 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 5677, pricingEngine_CustomerType0, true, (String) null, true, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(5677, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=0.0, quantity=5677, customerType=REGULAR, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2332, (-1213), pricingEngine_CustomerType0, false, "", false, 2);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 100, pricingEngine_CustomerType0, false, "", false, 1029);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=1.0, quantity=100, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=false, loyaltyPoints=1029]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2146441084, pricingEngine_CustomerType0, true, "SAVE10", true, 2146441084);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals("PricingRequest[basePrice=0.0, quantity=2146441084, customerType=REGULAR, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2146441084]", pricingEngine_PricingRequest0.toString());
      assertEquals(2146441084, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(682.0, 582, pricingEngine_CustomerType0, false, "save10", true, 3297);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals("PricingRequest[basePrice=682.0, quantity=582, customerType=REGULAR, seasonalSale=false, couponCode=save10, firstOrder=true, loyaltyPoints=3297]", pricingEngine_PricingRequest0.toString());
      assertEquals(3297, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2058.810032975863, 2, pricingEngine_CustomerType0, false, "Ar }@DV`a([Po$BM", false, 2);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=2058.810032975863, quantity=2, customerType=VIP, seasonalSale=false, couponCode=Ar }@DV`a([Po$BM, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2332, pricingEngine_CustomerType0, false, " 2AuwOZ", true, 2);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=0.0, quantity=2332, customerType=REGULAR, seasonalSale=false, couponCode= 2AuwOZ, firstOrder=true, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 5677, pricingEngine_CustomerType0, true, (String) null, true, 0);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=0.0, quantity=5677, customerType=REGULAR, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 100, pricingEngine_CustomerType0, false, "", false, 1029);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=1.0, quantity=100, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=false, loyaltyPoints=1029]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2423, 2146441084, pricingEngine_CustomerType0, true, "SAVE10", true, 2198);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(3.38053738525379E12, double0, 0.01);
      assertEquals(2198, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=2423.0, quantity=2146441084, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2198]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(243, 243, pricingEngine_CustomerType0, true, "FLAT5", true, 243);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(38384.84, double0, 0.01);
      assertEquals("PricingRequest[basePrice=243.0, quantity=243, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=243]", pricingEngine_PricingRequest0.toString());
      assertEquals(243, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2146441084, pricingEngine_CustomerType0, false, "FLAT5", false, 2146441084);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=2146441084, customerType=REGULAR, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=2146441084]", pricingEngine_PricingRequest0.toString());
      assertEquals(2146441084, pricingEngine_PricingRequest0.quantity());
      assertEquals(2146441084, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 100, pricingEngine_CustomerType0, true, (String) null, false, 100);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1.0, quantity=100, customerType=VIP, seasonalSale=true, couponCode=null, firstOrder=false, loyaltyPoints=100]", pricingEngine_PricingRequest0.toString());
      assertEquals(100, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(72.99, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2, 2, pricingEngine_CustomerType0, false, "", false, 2);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(11.99, double0, 0.01);
      assertEquals(2, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 44, pricingEngine_CustomerType0, false, "FREESHIP", true, 2146441084);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(44, pricingEngine_PricingRequest0.quantity());
      assertEquals(2146441084, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=44, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=2146441084]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2, 2, pricingEngine_CustomerType0, true, "9", true, 2);
      assertEquals(2.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=2.0, quantity=2, customerType=VIP, seasonalSale=true, couponCode=9, firstOrder=true, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertEquals(2, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(10.71, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(28, 28, pricingEngine_CustomerType0, false, "[w/V!1p'93:n]DKh(l", false, (-646));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(243, 243, (PricingEngine.CustomerType) null, false, "4", false, 243);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 0, pricingEngine_CustomerType0, true, "FLAT5", true, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-1635), 1462, pricingEngine_CustomerType0, true, "FLAT5", true, 2147483062);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(682.0, 582, pricingEngine_CustomerType0, false, "save10", true, 3297);
      Object object0 = new Object();
      pricingEngine_PricingRequest0.equals(object0);
      assertEquals("PricingRequest[basePrice=682.0, quantity=582, customerType=REGULAR, seasonalSale=false, couponCode=save10, firstOrder=true, loyaltyPoints=3297]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2146441084, pricingEngine_CustomerType0, true, "SAVE10", true, 2146441084);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=0.0, quantity=2146441084, customerType=REGULAR, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2146441084]", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2146441084, pricingEngine_CustomerType0, true, "SAVE10", true, 2146441084);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2146441084, pricingEngine_PricingRequest0.quantity());
      assertEquals(2146441084, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals("PricingRequest[basePrice=0.0, quantity=2146441084, customerType=REGULAR, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2146441084]", pricingEngine_PricingRequest0.toString());
  }
}
