/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:02:44 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.LruCache;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class LruCache_ESTest extends LruCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = new LruCache<Integer, Integer>(1);
      Integer integer0 = new Integer(1);
      lruCache0.put(integer0, (Integer) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = null;
      try {
        lruCache0 = new LruCache<Integer, Integer>(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity must be > 0
         //
         verifyException("com.viktor.lab4.LruCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = new LruCache<Integer, Integer>(3531);
      Integer integer0 = new Integer((-1));
      lruCache0.put(integer0, integer0);
      int int0 = lruCache0.size();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = new LruCache<Integer, Integer>(1);
      Integer integer0 = new Integer(1);
      Integer integer1 = lruCache0.get(integer0);
      lruCache0.put(integer1, (Integer) null);
      lruCache0.put(integer0, integer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = null;
      try {
        lruCache0 = new LruCache<Integer, Integer>((-2629));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // capacity must be > 0
         //
         verifyException("com.viktor.lab4.LruCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = new LruCache<Integer, Integer>(3531);
      Integer integer0 = new Integer((-1));
      boolean boolean0 = lruCache0.containsKey(integer0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = new LruCache<Integer, Integer>(3531);
      Integer integer0 = new Integer((-1));
      lruCache0.put(integer0, integer0);
      boolean boolean0 = lruCache0.containsKey(integer0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      LruCache<Integer, Integer> lruCache0 = new LruCache<Integer, Integer>(298);
      int int0 = lruCache0.size();
      assertEquals(0, int0);
  }
}
