/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 19:57:08 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1143.349, 1937, pricingEngine_CustomerType0, false, "I`++:hO#@", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=1143.349, quantity=1937, customerType=VIP, seasonalSale=false, couponCode=I`++:hO#@, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(1727448.26, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5.0, 0, pricingEngine_CustomerType0, true, "", true, (-2050));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(329.083, 541, pricingEngine_CustomerType0, true, "", false, 541);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=329.083, quantity=541, customerType=REGULAR, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=541]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(329.083, 1, pricingEngine_CustomerType0, false, "SAVE10", true, 541);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals(1, int0);
      assertEquals("PricingRequest[basePrice=329.083, quantity=1, customerType=VIP, seasonalSale=false, couponCode=SAVE10, firstOrder=true, loyaltyPoints=541]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(329.083, 541, pricingEngine_CustomerType0, true, "", false, 541);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals(541, int0);
      assertEquals("PricingRequest[basePrice=329.083, quantity=541, customerType=REGULAR, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=541]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 0, pricingEngine_CustomerType0, true, "", true, 0);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=0.0, quantity=0, customerType=REGULAR, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(329.083, 541, pricingEngine_CustomerType0, true, "", false, 541);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=329.083, quantity=541, customerType=REGULAR, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=541]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2487.8334981, 10, pricingEngine_CustomerType0, true, "quantity must be > 0", true, 10);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=2487.8334981, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=quantity must be > 0, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2487.8334981, 10, pricingEngine_CustomerType0, true, "quantity must be > 0", true, 10);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=2487.8334981, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=quantity must be > 0, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2058, pricingEngine_CustomerType0, false, "FREESHIP", false, 2083236204);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2083236204, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=2058, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=2083236204]", pricingEngine_PricingRequest0.toString());
      assertEquals(2058, pricingEngine_PricingRequest0.quantity());
      assertFalse(pricingEngine_PricingRequest0.firstOrder());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2929, 2929, pricingEngine_CustomerType0, false, "FLAT5", false, 2929);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2929, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=2929.0, quantity=2929, customerType=REGULAR, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=2929]", pricingEngine_PricingRequest0.toString());
      assertEquals(7292187.84, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2028, 802, pricingEngine_CustomerType0, true, "SAVE10", true, 2028);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=2028.0, quantity=802, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2028]", pricingEngine_PricingRequest0.toString());
      assertEquals(2028, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1057204.39, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 264, pricingEngine_CustomerType0, true, "save10", true, 264);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=264, customerType=VIP, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=264]", pricingEngine_PricingRequest0.toString());
      assertEquals(264, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(264, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2058, 2058, pricingEngine_CustomerType0, true, "", true, 2058);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2752994.59, double0, 0.01);
      assertEquals("PricingRequest[basePrice=2058.0, quantity=2058, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=2058]", pricingEngine_PricingRequest0.toString());
      assertEquals(2058, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(977, 977, pricingEngine_CustomerType0, false, (String) null, false, 977);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(696814.16, double0, 0.01);
      assertEquals("PricingRequest[basePrice=977.0, quantity=977, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=977]", pricingEngine_PricingRequest0.toString());
      assertEquals(977, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1, pricingEngine_CustomerType0, false, "GoV!", false, 1);
      assertEquals(1.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=VIP, seasonalSale=false, couponCode=GoV!, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals(8.87, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2058, 2058, pricingEngine_CustomerType0, true, "FREESHIP", true, (-1725996277));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2058, (PricingEngine.CustomerType) null, false, "FREESHIP", false, 2058);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(457.530828492, (-283), pricingEngine_CustomerType0, false, "=dh{hI:XS4R0V", false, (-283));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-1057.51367), 20, pricingEngine_CustomerType0, true, "", true, 20);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "@Q\"%", true, 10);
      pricingEngine_PricingRequest0.equals("");
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=VIP, seasonalSale=true, couponCode=@Q\"%, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "@Q\"%", true, 10);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=VIP, seasonalSale=true, couponCode=@Q\"%, firstOrder=true, loyaltyPoints=10]", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2089, pricingEngine_CustomerType0, true, "FLAT5", true, 2089);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=2089, customerType=REGULAR, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=2089]", pricingEngine_PricingRequest0.toString());
      assertEquals(2089, pricingEngine_PricingRequest0.quantity());
      assertEquals(2089, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
  }
}
