/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:07:29 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 20, pricingEngine_CustomerType0, true, "", true, 0);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(20, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=0.0, quantity=20, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 0, pricingEngine_CustomerType0, true, "!3jDq<zx", true, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4689.2397, 1309, pricingEngine_CustomerType0, true, "SAVE10", true, 1309);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=4689.2397, quantity=1309, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=1309]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(620.1117046375434, 3624, pricingEngine_CustomerType0, false, "FLAT5", false, 3624);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals("PricingRequest[basePrice=620.1117046375434, quantity=3624, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=3624]", pricingEngine_PricingRequest0.toString());
      assertEquals(3624, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 1557, pricingEngine_CustomerType0, false, "v48d", false, 1557);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals(1557, int0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=1557, customerType=REGULAR, seasonalSale=false, couponCode=v48d, firstOrder=false, loyaltyPoints=1557]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.35, 1197, pricingEngine_CustomerType0, false, "C|H+,RMZ&q/", false, 1197);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=0.35, quantity=1197, customerType=REGULAR, seasonalSale=false, couponCode=C|H+,RMZ&q/, firstOrder=false, loyaltyPoints=1197]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 2141601702, pricingEngine_CustomerType0, false, (String) null, false, 0);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=0.0, quantity=2141601702, customerType=REGULAR, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(620.1117046375434, 3624, pricingEngine_CustomerType0, false, "FLAT5", false, 3624);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=620.1117046375434, quantity=3624, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=3624]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(620.1117046375434, 3624, pricingEngine_CustomerType0, false, "FLAT5", false, 3624);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=620.1117046375434, quantity=3624, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=3624]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2146604582, pricingEngine_CustomerType0, false, "FLAT5", false, 1);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(2146604582, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=0.0, quantity=2146604582, customerType=REGULAR, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 100, pricingEngine_CustomerType0, false, "FLAT5", true, 2146940668);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1.0, quantity=100, customerType=REGULAR, seasonalSale=false, couponCode=FLAT5, firstOrder=true, loyaltyPoints=2146940668]", pricingEngine_PricingRequest0.toString());
      assertEquals(2146940668, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(82.99, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.1, 399, pricingEngine_CustomerType0, true, "SAVE10", true, 607);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.1, quantity=399, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=607]", pricingEngine_PricingRequest0.toString());
      assertEquals(33.93, double0, 0.01);
      assertEquals(607, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(357707.99, 20, pricingEngine_CustomerType0, true, "SAVE10", true, 20);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=357707.99, quantity=20, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=20]", pricingEngine_PricingRequest0.toString());
      assertEquals(20, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(4650211.86, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5.0, 1102, pricingEngine_CustomerType0, false, (String) null, false, 1102);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1102, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(4030.29, double0, 0.01);
      assertEquals("PricingRequest[basePrice=5.0, quantity=1102, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=1102]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1811.0, 1, pricingEngine_CustomerType0, true, "", true, 1);
      assertEquals(1811.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1811.0, quantity=1, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1239.47, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1494.5295953, 835, pricingEngine_CustomerType0, true, "8d .kc", true, (-653));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2037.6, (-1741), pricingEngine_CustomerType0, true, "", true, (-1741));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-1166), (-2268), pricingEngine_CustomerType0, true, "8t2b5q{ZQ-RG&xr8$", true, 1);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.1, 399, pricingEngine_CustomerType0, true, "SAVE10", true, 607);
      pricingEngine_PricingRequest0.equals(pricingEngine0);
      assertEquals("PricingRequest[basePrice=0.1, quantity=399, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=607]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4689.2397, 1309, pricingEngine_CustomerType0, true, "SAVE10", true, 1309);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=4689.2397, quantity=1309, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=1309]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 700, pricingEngine_CustomerType0, false, "FREESHIP", false, 5);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=700, customerType=VIP, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=5]", pricingEngine_PricingRequest0.toString());
      assertEquals(5, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(700, pricingEngine_PricingRequest0.quantity());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
  }
}
