/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 17:05:00 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(170.0, 311, pricingEngine_CustomerType0, true, "REQUEST MUST NOT BE NULL", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(34373.49, double0, 0.01);
      assertEquals("PricingRequest[basePrice=170.0, quantity=311, customerType=VIP, seasonalSale=true, couponCode=REQUEST MUST NOT BE NULL, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, (-428), pricingEngine_CustomerType0, true, "%^Fb71aTIl", true, (-428));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, "", true, 10);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, "", true, 10);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals(10, int0);
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2232.957317, 200, pricingEngine_CustomerType0, false, "", false, 200);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=2232.957317, quantity=200, customerType=VIP, seasonalSale=false, couponCode=, firstOrder=false, loyaltyPoints=200]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 605, pricingEngine_CustomerType0, false, (String) null, false, 605);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=0.0, quantity=605, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=605]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1266.1402, 3787, pricingEngine_CustomerType0, false, "FLAT5", true, 10);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1266.1402, quantity=3787, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(3500260.23, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2147461797, 2147461797, pricingEngine_CustomerType0, true, "save10", true, 2147461797);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2147461797, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=2.147461797E9, quantity=2147461797, customerType=VIP, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=2147461797]", pricingEngine_PricingRequest0.toString());
      assertEquals(2147461797, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(22.0, 1, pricingEngine_CustomerType0, true, "save10", true, 1);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=22.0, quantity=1, customerType=REGULAR, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(25.59, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(22, 22, pricingEngine_CustomerType0, false, "", false, 22);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(22, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(443.59, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(65, 65, pricingEngine_CustomerType0, false, (String) null, false, 65);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(65, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(3303.49, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, (-2921));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 17, (PricingEngine.CustomerType) null, true, "$',]z:8trzIG", true, 17);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 0, pricingEngine_CustomerType0, false, "FREESHIP", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-12), (-12), pricingEngine_CustomerType0, false, "FREESHIP", false, (-12));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 2, pricingEngine_CustomerType0, false, "AshiTEx(c", false, 2);
      Object object0 = new Object();
      pricingEngine_PricingRequest0.equals(object0);
      assertEquals("PricingRequest[basePrice=1.0, quantity=2, customerType=VIP, seasonalSale=false, couponCode=AshiTEx(c, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2, 2, pricingEngine_CustomerType0, true, "FLAT5", true, 2);
      assertEquals(2.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=2.0, quantity=2, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertEquals(2, pricingEngine_PricingRequest0.quantity());
      assertEquals(2, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(10.71, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 368, pricingEngine_CustomerType0, false, "save10", false, 2146722648);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=0.0, quantity=368, customerType=VIP, seasonalSale=false, couponCode=save10, firstOrder=false, loyaltyPoints=2146722648]", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }
}
