/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 19:39:36 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.SimpleJsonParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleJsonParser_ESTest extends SimpleJsonParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[7_02JI");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got '_' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("2:IOB\u0003Q0s:m");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("!.SBc;2^1%VKRDRB3");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token '!' at position 0
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse(" a]\"WxG");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token 'a' at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[]ru^$H");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("1.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[7)02JI");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got ')' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"<{^~dL!\rJF");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated string literal at position 11
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"4$|3U\"0^_?8|QP5");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 7
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"}\\MT2ViY");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported escape sequence \\M at position 4
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[j'/9cL.u");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token 'j' at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected end of input at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      Object object0 = simpleJsonParser0.parse("3");
      assertEquals(3.0, object0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input must not be null
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[02");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated array at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }
}
