/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 17:01:35 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(170.0, 311, pricingEngine_CustomerType0, true, "REQUEST MUST NOT BE NULL", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=170.0, quantity=311, customerType=VIP, seasonalSale=true, couponCode=REQUEST MUST NOT BE NULL, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(34373.49, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, (-428), pricingEngine_CustomerType0, true, "%^Fb71aTIl", true, (-428));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, "", true, 10);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, false, "", true, 10);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2232.957317, 200, pricingEngine_CustomerType0, false, "", false, 200);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=2232.957317, quantity=200, customerType=VIP, seasonalSale=false, couponCode=, firstOrder=false, loyaltyPoints=200]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 605, pricingEngine_CustomerType0, false, (String) null, false, 605);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=0.0, quantity=605, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=605]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1266.1402, 3787, pricingEngine_CustomerType0, false, "FLAT5", true, 10);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(3500260.23, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 689, pricingEngine_CustomerType0, true, (String) null, true, 689);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=689, customerType=VIP, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=689]", pricingEngine_PricingRequest0.toString());
      assertEquals(689, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(689, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(20.0, 1091, pricingEngine_CustomerType0, true, "SAVE10", true, 1091);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1091, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(14190.99, double0, 0.01);
      assertEquals("PricingRequest[basePrice=20.0, quantity=1091, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=1091]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, true, (String) null, true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(72.99, double0, 0.01);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=10.0, quantity=10, customerType=VIP, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, true, "", true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(77.99, double0, 0.01);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5, 5, pricingEngine_CustomerType0, false, "FREESHIP", false, 5);
      assertEquals(5.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=5.0, quantity=5, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=false, loyaltyPoints=5]", pricingEngine_PricingRequest0.toString());
      assertEquals(25.0, double0, 0.01);
      assertEquals(5, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 3, pricingEngine_CustomerType0, false, "save10", false, 3);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=3, customerType=VIP, seasonalSale=false, couponCode=save10, firstOrder=false, loyaltyPoints=3]", pricingEngine_PricingRequest0.toString());
      assertEquals(3, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals(3, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, true, "FREESHIP", true, (-2921));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, (PricingEngine.CustomerType) null, true, "$Y7-jWEaDv|", true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 0, pricingEngine_CustomerType0, false, "FREESHIP", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-951), (-951), pricingEngine_CustomerType0, false, "FREESHIP", false, (-951));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 2, pricingEngine_CustomerType0, false, "AshiTEx(c", false, 2);
      Object object0 = new Object();
      pricingEngine_PricingRequest0.equals(object0);
      assertEquals("PricingRequest[basePrice=1.0, quantity=2, customerType=VIP, seasonalSale=false, couponCode=AshiTEx(c, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 10, pricingEngine_CustomerType0, false, "FLAT5", false, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(10, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 368, pricingEngine_CustomerType0, false, "save10", false, 2146722648);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=0.0, quantity=368, customerType=VIP, seasonalSale=false, couponCode=save10, firstOrder=false, loyaltyPoints=2146722648]", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }
}
