/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 19:57:52 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1602.0, 856, pricingEngine_CustomerType0, false, (String) null, true, 0);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1602.0, quantity=856, customerType=REGULAR, seasonalSale=false, couponCode=null, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1165623.19, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 0, pricingEngine_CustomerType0, true, "N|5", false, 814);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, (-932), pricingEngine_CustomerType0, true, (String) null, true, (-932));
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals("PricingRequest[basePrice=0.0, quantity=-932, customerType=VIP, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=-932]", pricingEngine_PricingRequest0.toString());
      assertEquals((-932), int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(38, 38, pricingEngine_CustomerType0, true, "freeship", true, 38);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=38.0, quantity=38, customerType=VIP, seasonalSale=true, couponCode=freeship, firstOrder=true, loyaltyPoints=38]", pricingEngine_PricingRequest0.toString());
      assertEquals(38, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(938.6, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2, 100, pricingEngine_CustomerType0, false, (String) null, true, 2);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=2.0, quantity=100, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=true, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
      assertEquals(2, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(153.99, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1, 1, pricingEngine_CustomerType0, false, "FLAT5", false, 1);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(8.87, double0, 0.01);
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(24, 24, pricingEngine_CustomerType0, false, "save10", false, 24);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(24, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(468.79, double0, 0.01);
      assertEquals("PricingRequest[basePrice=24.0, quantity=24, customerType=REGULAR, seasonalSale=false, couponCode=save10, firstOrder=false, loyaltyPoints=24]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2870, 2870, pricingEngine_CustomerType0, false, "", false, 2870);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2870, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(7001372.99, double0, 0.01);
      assertEquals("PricingRequest[basePrice=2870.0, quantity=2870, customerType=REGULAR, seasonalSale=false, couponCode=, firstOrder=false, loyaltyPoints=2870]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(20.0, 1, pricingEngine_CustomerType0, true, "FLAT5", true, 1);
      assertEquals(20.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=20.0, quantity=1, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals(16.59, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 5, pricingEngine_CustomerType0, false, "freeship", false, 5);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals(5, pricingEngine_PricingRequest0.quantity());
      assertEquals(5, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=5, customerType=REGULAR, seasonalSale=false, couponCode=freeship, firstOrder=false, loyaltyPoints=5]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5, 5, pricingEngine_CustomerType0, false, "HQZ$BJ0W=", false, (-1612818004));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 11, (PricingEngine.CustomerType) null, false, "freeship", false, 33);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(728.803368004409, (-2979), pricingEngine_CustomerType0, true, "`F5V;He;5", true, (-2979));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-9), (-9), pricingEngine_CustomerType0, false, "jr,Li>HRgnx,?8Y`k", false, (-9));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      pricingEngine_PricingRequest0.equals(".\"j/`R5`_I,,]9l}");
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(277.88858, 1144, pricingEngine_CustomerType0, false, ".\"j/`R5`_I,,]9l}", false, 2);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=277.88858, quantity=1144, customerType=VIP, seasonalSale=false, couponCode=.\"j/`R5`_I,,]9l}, firstOrder=false, loyaltyPoints=2]", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 1488, pricingEngine_CustomerType0, false, "SAVE10", false, 1488);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=1488, customerType=VIP, seasonalSale=false, couponCode=SAVE10, firstOrder=false, loyaltyPoints=1488]", pricingEngine_PricingRequest0.toString());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals(1488, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1488, pricingEngine_PricingRequest0.quantity());
  }
}
