/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 17:41:14 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.SimpleJsonParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleJsonParser_ESTest extends SimpleJsonParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[4G{q");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got 'G' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[u\"JjL(=llCl2=\"lP");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token 'u' at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("!q{d45PdMx'");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token '!' at position 0
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[4{");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got '{' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[4]g&r^O~s&Z");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[]`G");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("6.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"yLzf.D<{\fAA'L");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated string literal at position 14
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected end of input at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      Object object0 = simpleJsonParser0.parse("\"\"");
      assertEquals("", object0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input must not be null
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("5 8{D.H6]W-TeC60@pS");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[4");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated array at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }
}
