/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:13:32 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1312.073895635313, 1, pricingEngine_CustomerType0, false, "SAVE10", true, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1312.073895635313, quantity=1, customerType=REGULAR, seasonalSale=false, couponCode=SAVE10, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1, pricingEngine_PricingRequest0.quantity());
      assertEquals(1123.25, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(823.4, 0, pricingEngine_CustomerType0, false, "Cts", true, 0);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1312.073895635313, 1, pricingEngine_CustomerType0, false, "SAVE10", true, 0);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=1312.073895635313, quantity=1, customerType=REGULAR, seasonalSale=false, couponCode=SAVE10, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(846.68982, 80, pricingEngine_CustomerType0, true, "1", true, 80);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals(80, int0);
      assertEquals("PricingRequest[basePrice=846.68982, quantity=80, customerType=REGULAR, seasonalSale=true, couponCode=1, firstOrder=true, loyaltyPoints=80]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(846.68982, 80, pricingEngine_CustomerType0, true, "1", true, 80);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals(80, int0);
      assertEquals("PricingRequest[basePrice=846.68982, quantity=80, customerType=REGULAR, seasonalSale=true, couponCode=1, firstOrder=true, loyaltyPoints=80]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(846.68982, 80, pricingEngine_CustomerType0, true, "1", true, 80);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=846.68982, quantity=80, customerType=REGULAR, seasonalSale=true, couponCode=1, firstOrder=true, loyaltyPoints=80]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(846.68982, 80, pricingEngine_CustomerType0, true, "1", true, 80);
      pricingEngine_PricingRequest0.customerType();
      assertEquals("PricingRequest[basePrice=846.68982, quantity=80, customerType=REGULAR, seasonalSale=true, couponCode=1, firstOrder=true, loyaltyPoints=80]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1691.2358078482703, 1388, pricingEngine_CustomerType0, true, "", false, 1388);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=1691.2358078482703, quantity=1388, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=1388]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.35, 1, pricingEngine_CustomerType0, true, "SAVE10", false, 1);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=0.35, quantity=1, customerType=REGULAR, seasonalSale=true, couponCode=SAVE10, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 10, pricingEngine_CustomerType0, false, "FREESHIP", true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(10, pricingEngine_PricingRequest0.quantity());
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=false, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1583.978839544917, 2147483645, pricingEngine_CustomerType0, true, "SAVE10", true, 2147483645);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(2147483645, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(2.2110196237747E12, double0, 0.01);
      assertEquals("PricingRequest[basePrice=1583.978839544917, quantity=2147483645, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2147483645]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(12013.666083, 1560, pricingEngine_CustomerType0, true, (String) null, true, 1560);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=12013.666083, quantity=1560, customerType=VIP, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=1560]", pricingEngine_PricingRequest0.toString());
      assertEquals(1.21818654E7, double0, 0.01);
      assertEquals(1560, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(4830.99, 2147483645, pricingEngine_CustomerType0, false, "FLAT5", false, 2147483645);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(8.81830121203776E12, double0, 0.01);
      assertEquals(2147483645, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 10, pricingEngine_CustomerType0, true, "save10", false, 10);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=1.0, quantity=10, customerType=VIP, seasonalSale=true, couponCode=save10, firstOrder=false, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(14.49, double0, 0.01);
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1691.2358078482703, 1388, pricingEngine_CustomerType0, true, "", false, 1388);
      assertEquals(1691.2358078482703, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1388, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=1691.2358078482703, quantity=1388, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=1388]", pricingEngine_PricingRequest0.toString());
      assertEquals(1525840.94, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 10, pricingEngine_CustomerType0, true, "FLAT5", true, 10);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertEquals("PricingRequest[basePrice=0.0, quantity=10, customerType=REGULAR, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=10]", pricingEngine_PricingRequest0.toString());
      assertEquals(10, pricingEngine_PricingRequest0.quantity());
      assertEquals(10, pricingEngine_PricingRequest0.loyaltyPoints());
      assertTrue(pricingEngine_PricingRequest0.firstOrder());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(10, 10, pricingEngine_CustomerType0, true, ". ", true, (-421));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.12, 2780, (PricingEngine.CustomerType) null, false, "y!iW/CyW@x>t", true, (-1967));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(100.0, (-1796531106), pricingEngine_CustomerType0, false, "RJ&RbW(", false, (-1796531106));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-15), (-15), pricingEngine_CustomerType0, false, "v2E~`|", false, (-15));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1312.073895635313, 1, pricingEngine_CustomerType0, false, "SAVE10", true, 0);
      pricingEngine_PricingRequest0.equals("SAVE10");
      assertEquals("PricingRequest[basePrice=1312.073895635313, quantity=1, customerType=REGULAR, seasonalSale=false, couponCode=SAVE10, firstOrder=true, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2566.0427, 947, pricingEngine_CustomerType0, true, "]u7I*e@4'4%f^", false, 947);
      pricingEngine_PricingRequest0.toString();
      assertTrue(pricingEngine_PricingRequest0.seasonalSale());
      assertEquals(2566.0427, pricingEngine_PricingRequest0.basePrice(), 0.01);
      assertFalse(pricingEngine_PricingRequest0.firstOrder());
      assertEquals(947, pricingEngine_PricingRequest0.quantity());
      assertEquals(947, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }
}
