/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 19:47:21 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.SimpleJsonParser;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleJsonParser_ESTest extends SimpleJsonParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[8sZ#]Sc,i|g");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got 's' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[^lxd^R)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token '^' at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("0nM{hWWLHng`(/c");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("!|w?(Zecs9");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported token '!' at position 0
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"EiH");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated string literal at position 4
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse(" ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected end of input at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[5");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated array at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      ArrayList arrayList0 = (ArrayList)simpleJsonParser0.parse("[]");
      assertEquals(0, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("5.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 2
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[8#s]Sc,i|g");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected ',' or ']' in array but got '#' at position 3
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"w'B\tD");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unterminated string literal at position 6
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"]LT(\\ ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unsupported escape sequence \\  at position 7
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Expected digit at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("[");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected end of input at position 1
         //
         verifyException("com.viktor.lab4.SimpleJsonParser$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // input must not be null
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SimpleJsonParser simpleJsonParser0 = new SimpleJsonParser();
      // Undeclared exception!
      try { 
        simpleJsonParser0.parse("\"xgs\"iOH");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Unexpected trailing characters at position 5
         //
         verifyException("com.viktor.lab4.SimpleJsonParser", e);
      }
  }
}
