/*
 * This file was automatically generated by EvoSuite
 * Fri May 29 18:08:38 GMT 2026
 */

package com.viktor.lab4;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.viktor.lab4.PricingEngine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PricingEngine_ESTest extends PricingEngine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2010, pricingEngine_CustomerType0, false, "wSPVv{k,`MHqy/<", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=2010, customerType=VIP, seasonalSale=false, couponCode=wSPVv{k,`MHqy/<, firstOrder=false, loyaltyPoints=0]", pricingEngine_PricingRequest0.toString());
      assertEquals(2010, pricingEngine_PricingRequest0.quantity());
      assertEquals(0, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(650, (-1683), pricingEngine_CustomerType0, false, "('d8$", true, (-1683));
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1, pricingEngine_CustomerType0, true, "FLAT5", false, 1);
      boolean boolean0 = pricingEngine_PricingRequest0.seasonalSale();
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 2856, pricingEngine_CustomerType0, true, "", true, 2856);
      int int0 = pricingEngine_PricingRequest0.quantity();
      assertEquals(2856, int0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=2856, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=true, loyaltyPoints=2856]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1124.85767, 1008, pricingEngine_CustomerType0, true, "", false, 1008);
      int int0 = pricingEngine_PricingRequest0.loyaltyPoints();
      assertEquals(1008, int0);
      assertEquals("PricingRequest[basePrice=1124.85767, quantity=1008, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=1008]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1124.85767, 1008, pricingEngine_CustomerType0, true, "", false, 1008);
      boolean boolean0 = pricingEngine_PricingRequest0.firstOrder();
      assertEquals("PricingRequest[basePrice=1124.85767, quantity=1008, customerType=VIP, seasonalSale=true, couponCode=, firstOrder=false, loyaltyPoints=1008]", pricingEngine_PricingRequest0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(645.07, 244, pricingEngine_CustomerType0, true, (String) null, true, 244);
      pricingEngine_PricingRequest0.couponCode();
      assertEquals("PricingRequest[basePrice=645.07, quantity=244, customerType=REGULAR, seasonalSale=true, couponCode=null, firstOrder=true, loyaltyPoints=244]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1, pricingEngine_CustomerType0, true, "FLAT5", false, 1);
      pricingEngine_PricingRequest0.basePrice();
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=false, loyaltyPoints=1]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1, pricingEngine_CustomerType0, true, "FLAT5", false, 1);
      PricingEngine.CustomerType pricingEngine_CustomerType1 = pricingEngine_PricingRequest0.customerType();
      PricingEngine.PricingRequest pricingEngine_PricingRequest1 = new PricingEngine.PricingRequest(1141.605242263, 1625, pricingEngine_CustomerType1, false, "FLAT5", true, 2144139124);
      PricingEngine pricingEngine0 = new PricingEngine();
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest1);
      assertEquals(1, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(1261476.78, double0, 0.01);
      assertEquals("PricingRequest[basePrice=1141.605242263, quantity=1625, customerType=VIP, seasonalSale=false, couponCode=FLAT5, firstOrder=true, loyaltyPoints=2144139124]", pricingEngine_PricingRequest1.toString());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 5, pricingEngine_CustomerType0, true, "FREESHIP", true, 1922);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(1922, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=0.0, quantity=5, customerType=REGULAR, seasonalSale=true, couponCode=FREESHIP, firstOrder=true, loyaltyPoints=1922]", pricingEngine_PricingRequest0.toString());
      assertEquals(5, pricingEngine_PricingRequest0.quantity());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 6, pricingEngine_CustomerType0, true, "FLAT5", true, 6);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=6, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=true, loyaltyPoints=6]", pricingEngine_PricingRequest0.toString());
      assertEquals(6, pricingEngine_PricingRequest0.quantity());
      assertEquals(6, pricingEngine_PricingRequest0.loyaltyPoints());
      assertTrue(pricingEngine_PricingRequest0.seasonalSale());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(156227.45748889, 2206, pricingEngine_CustomerType0, true, "SAVE10", true, 2206);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=156227.45748889, quantity=2206, customerType=VIP, seasonalSale=true, couponCode=SAVE10, firstOrder=true, loyaltyPoints=2206]", pricingEngine_PricingRequest0.toString());
      assertEquals(2.2401455928E8, double0, 0.01);
      assertEquals(2206, pricingEngine_PricingRequest0.loyaltyPoints());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(5, 5, pricingEngine_CustomerType0, true, "", true, 5);
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(5, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(24.99, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2996.5701619120987, 1908608937, pricingEngine_CustomerType0, false, (String) null, false, 1908608937);
      assertEquals(2996.5701619120987, pricingEngine_PricingRequest0.basePrice(), 0.01);
      
      double double0 = pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals(4.17507483171026E12, double0, 0.01);
      assertEquals(1908608937, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals("PricingRequest[basePrice=2996.5701619120987, quantity=1908608937, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=1908608937]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(2147480290, 2147480290, pricingEngine_CustomerType0, false, "kqN_C,@hm2aGg=Q>", false, (-1));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // loyaltyPoints must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 5, (PricingEngine.CustomerType) null, true, (String) null, true, 5);
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // customerType must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0, 0, pricingEngine_CustomerType0, false, "kqN_C,@hm2aGg=Q>", false, 0);
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // quantity must be > 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.REGULAR;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest((-16), (-16), pricingEngine_CustomerType0, true, "M}xn3{%Z1V", true, (-16));
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // basePrice must be >= 0
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      // Undeclared exception!
      try { 
        pricingEngine0.calculateFinalPrice((PricingEngine.PricingRequest) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // request must not be null
         //
         verifyException("com.viktor.lab4.PricingEngine", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(645.07, 242, pricingEngine_CustomerType0, false, (String) null, false, 242);
      PricingEngine pricingEngine0 = new PricingEngine();
      pricingEngine_PricingRequest0.equals(pricingEngine0);
      assertEquals("PricingRequest[basePrice=645.07, quantity=242, customerType=VIP, seasonalSale=false, couponCode=null, firstOrder=false, loyaltyPoints=242]", pricingEngine_PricingRequest0.toString());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(1.0, 1, pricingEngine_CustomerType0, true, "FLAT5", false, 1);
      String string0 = pricingEngine_PricingRequest0.toString();
      assertEquals("PricingRequest[basePrice=1.0, quantity=1, customerType=VIP, seasonalSale=true, couponCode=FLAT5, firstOrder=false, loyaltyPoints=1]", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      PricingEngine pricingEngine0 = new PricingEngine();
      PricingEngine.CustomerType pricingEngine_CustomerType0 = PricingEngine.CustomerType.VIP;
      PricingEngine.PricingRequest pricingEngine_PricingRequest0 = new PricingEngine.PricingRequest(0.0, 5, pricingEngine_CustomerType0, true, "save10", true, 5);
      pricingEngine0.calculateFinalPrice(pricingEngine_PricingRequest0);
      assertEquals("PricingRequest[basePrice=0.0, quantity=5, customerType=VIP, seasonalSale=true, couponCode=save10, firstOrder=true, loyaltyPoints=5]", pricingEngine_PricingRequest0.toString());
      assertEquals(5, pricingEngine_PricingRequest0.loyaltyPoints());
      assertEquals(5, pricingEngine_PricingRequest0.quantity());
      assertEquals(0.0, pricingEngine_PricingRequest0.basePrice(), 0.01);
  }
}
